/**
 * copyright (c) 2020 Kuta Service Framework
 * @author: mybatis generator
 */
package com.kuta.data.mysql.dao;

import com.kuta.data.mysql.pojo.Department;
import com.kuta.data.mysql.pojo.DepartmentExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DepartmentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BS_Department
     * @date 2021-08-22 14:53:49
     */
    long countByExample(DepartmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BS_Department
     * @date 2021-08-22 14:53:49
     */
    int deleteByExample(DepartmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BS_Department
     * @date 2021-08-22 14:53:49
     */
    int deleteByPrimaryKey(Integer did);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BS_Department
     * @date 2021-08-22 14:53:49
     */
    int insert(Department record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BS_Department
     * @date 2021-08-22 14:53:49
     */
    int insertSelective(Department record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BS_Department
     * @date 2021-08-22 14:53:49
     */
    List<Department> selectByExample(DepartmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BS_Department
     * @date 2021-08-22 14:53:49
     */
    Department selectByPrimaryKey(Integer did);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BS_Department
     * @date 2021-08-22 14:53:49
     */
    int updateByExampleSelective(@Param("record") Department record, @Param("example") DepartmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BS_Department
     * @date 2021-08-22 14:53:49
     */
    int updateByExample(@Param("record") Department record, @Param("example") DepartmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BS_Department
     * @date 2021-08-22 14:53:49
     */
    int updateByPrimaryKeySelective(Department record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BS_Department
     * @date 2021-08-22 14:53:49
     */
    int updateByPrimaryKey(Department record);

    /**
     * 这是Mybatis Generator拓展插件生成的方法(请勿删除).
     * This method corresponds to the database table BS_Department
     *
     * @mbg.generated
     * @author hewei
     */
    int batchInsert(@Param("list") List<Department> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BS_Department
     * @date 2021-08-22 14:53:49
     */
    int batchUpdate(@Param("recordList") List<Department> recordList);
}