/**
 * copyright (c) 2020 Kuta Service Framework
 * @author: mybatis generator
 */
package com.kuta.data.mysql.dao;

import com.kuta.data.mysql.pojo.Organization;
import com.kuta.data.mysql.pojo.OrganizationExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface OrganizationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BS_Organization
     * @date 2021-08-22 14:53:49
     */
    long countByExample(OrganizationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BS_Organization
     * @date 2021-08-22 14:53:49
     */
    int deleteByExample(OrganizationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BS_Organization
     * @date 2021-08-22 14:53:49
     */
    int deleteByPrimaryKey(Integer oid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BS_Organization
     * @date 2021-08-22 14:53:49
     */
    int insert(Organization record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BS_Organization
     * @date 2021-08-22 14:53:49
     */
    int insertSelective(Organization record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BS_Organization
     * @date 2021-08-22 14:53:49
     */
    List<Organization> selectByExample(OrganizationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BS_Organization
     * @date 2021-08-22 14:53:49
     */
    Organization selectByPrimaryKey(Integer oid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BS_Organization
     * @date 2021-08-22 14:53:49
     */
    int updateByExampleSelective(@Param("record") Organization record, @Param("example") OrganizationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BS_Organization
     * @date 2021-08-22 14:53:49
     */
    int updateByExample(@Param("record") Organization record, @Param("example") OrganizationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BS_Organization
     * @date 2021-08-22 14:53:49
     */
    int updateByPrimaryKeySelective(Organization record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BS_Organization
     * @date 2021-08-22 14:53:49
     */
    int updateByPrimaryKey(Organization record);

    /**
     * 这是Mybatis Generator拓展插件生成的方法(请勿删除).
     * This method corresponds to the database table BS_Organization
     *
     * @mbg.generated
     * @author hewei
     */
    int batchInsert(@Param("list") List<Organization> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BS_Organization
     * @date 2021-08-22 14:53:49
     */
    int batchUpdate(@Param("recordList") List<Organization> recordList);
}