/**
 * copyright (c) 2020 Kuta Service Framework
 * @author: mybatis generator
 */
package com.kuta.data.mysql.dao;

import com.kuta.data.mysql.pojo.Role;
import com.kuta.data.mysql.pojo.RoleExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BS_Role
     * @date 2021-12-13 00:27:34
     */
    long countByExample(RoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BS_Role
     * @date 2021-12-13 00:27:34
     */
    int deleteByExample(RoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BS_Role
     * @date 2021-12-13 00:27:34
     */
    int deleteByPrimaryKey(Integer rid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BS_Role
     * @date 2021-12-13 00:27:34
     */
    int insert(Role record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BS_Role
     * @date 2021-12-13 00:27:34
     */
    int insertSelective(Role record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BS_Role
     * @date 2021-12-13 00:27:34
     */
    List<Role> selectByExample(RoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BS_Role
     * @date 2021-12-13 00:27:34
     */
    Role selectByPrimaryKey(Integer rid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BS_Role
     * @date 2021-12-13 00:27:34
     */
    int updateByExampleSelective(@Param("record") Role record, @Param("example") RoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BS_Role
     * @date 2021-12-13 00:27:34
     */
    int updateByExample(@Param("record") Role record, @Param("example") RoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BS_Role
     * @date 2021-12-13 00:27:34
     */
    int updateByPrimaryKeySelective(Role record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BS_Role
     * @date 2021-12-13 00:27:34
     */
    int updateByPrimaryKey(Role record);

    /**
     * 这是Mybatis Generator拓展插件生成的方法(请勿删除).
     * This method corresponds to the database table BS_Role
     *
     * @mbg.generated
     * @author hewei
     */
    int batchInsert(@Param("list") List<Role> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BS_Role
     * @date 2021-12-13 00:27:34
     */
    int updateWithOptimisticLock(Role record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BS_Role
     * @date 2021-12-13 00:27:34
     */
    int batchUpdate(@Param("recordList") List<Role> recordList);
}