/**
 * copyright (c) 2020 Kuta Service Framework
 * @author: mybatis generator
 */
package com.kuta.data.mysql.dao;

import com.kuta.data.mysql.pojo.Script;
import com.kuta.data.mysql.pojo.ScriptExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ScriptMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BS_Script
     * @date 2021-12-28 00:51:29
     */
    long countByExample(ScriptExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BS_Script
     * @date 2021-12-28 00:51:29
     */
    int deleteByExample(ScriptExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BS_Script
     * @date 2021-12-28 00:51:29
     */
    int deleteByPrimaryKey(Long sid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BS_Script
     * @date 2021-12-28 00:51:29
     */
    int insert(Script record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BS_Script
     * @date 2021-12-28 00:51:29
     */
    int insertSelective(Script record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BS_Script
     * @date 2021-12-28 00:51:29
     */
    List<Script> selectByExample(ScriptExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BS_Script
     * @date 2021-12-28 00:51:29
     */
    Script selectByPrimaryKey(Long sid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BS_Script
     * @date 2021-12-28 00:51:29
     */
    int updateByExampleSelective(@Param("record") Script record, @Param("example") ScriptExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BS_Script
     * @date 2021-12-28 00:51:29
     */
    int updateByExample(@Param("record") Script record, @Param("example") ScriptExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BS_Script
     * @date 2021-12-28 00:51:29
     */
    int updateByPrimaryKeySelective(Script record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BS_Script
     * @date 2021-12-28 00:51:29
     */
    int updateByPrimaryKey(Script record);

    /**
     * 这是Mybatis Generator拓展插件生成的方法(请勿删除).
     * This method corresponds to the database table BS_Script
     *
     * @mbg.generated
     * @author hewei
     */
    int batchInsert(@Param("list") List<Script> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BS_Script
     * @date 2021-12-28 00:51:29
     */
    int updateWithOptimisticLock(Script record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BS_Script
     * @date 2021-12-28 00:51:29
     */
    int batchUpdate(@Param("recordList") List<Script> recordList);
}