/**
 * copyright (c) 2020 Kuta Service Framework
 * @author: mybatis generator
 */
package com.kuta.data.mysql.dao;

import com.kuta.data.mysql.pojo.ScriptCategory;
import com.kuta.data.mysql.pojo.ScriptCategoryExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ScriptCategoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BS_Script_Category
     * @date 2021-07-15 12:55:28
     */
    long countByExample(ScriptCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BS_Script_Category
     * @date 2021-07-15 12:55:28
     */
    int deleteByExample(ScriptCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BS_Script_Category
     * @date 2021-07-15 12:55:28
     */
    int deleteByPrimaryKey(Integer cid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BS_Script_Category
     * @date 2021-07-15 12:55:28
     */
    int insert(ScriptCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BS_Script_Category
     * @date 2021-07-15 12:55:28
     */
    int insertSelective(ScriptCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BS_Script_Category
     * @date 2021-07-15 12:55:28
     */
    List<ScriptCategory> selectByExample(ScriptCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BS_Script_Category
     * @date 2021-07-15 12:55:28
     */
    ScriptCategory selectByPrimaryKey(Integer cid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BS_Script_Category
     * @date 2021-07-15 12:55:28
     */
    int updateByExampleSelective(@Param("record") ScriptCategory record, @Param("example") ScriptCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BS_Script_Category
     * @date 2021-07-15 12:55:28
     */
    int updateByExample(@Param("record") ScriptCategory record, @Param("example") ScriptCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BS_Script_Category
     * @date 2021-07-15 12:55:28
     */
    int updateByPrimaryKeySelective(ScriptCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BS_Script_Category
     * @date 2021-07-15 12:55:28
     */
    int updateByPrimaryKey(ScriptCategory record);

    /**
     * 这是Mybatis Generator拓展插件生成的方法(请勿删除).
     * This method corresponds to the database table BS_Script_Category
     *
     * @mbg.generated
     * @author hewei
     */
    int batchInsert(@Param("list") List<ScriptCategory> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BS_Script_Category
     * @date 2021-07-15 12:55:28
     */
    int batchUpdate(@Param("recordList") List<ScriptCategory> recordList);
}