/**
 * copyright (c) 2020 Kuta Service Framework
 * @author: mybatis generator
 */
package com.kuta.data.mysql.dao;

import com.kuta.data.mysql.pojo.UserPermRelExample;
import com.kuta.data.mysql.pojo.UserPermRelKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserPermRelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BS_UserPermRel
     * @date 2021-11-18 12:08:30
     */
    long countByExample(UserPermRelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BS_UserPermRel
     * @date 2021-11-18 12:08:30
     */
    int deleteByExample(UserPermRelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BS_UserPermRel
     * @date 2021-11-18 12:08:30
     */
    int deleteByPrimaryKey(UserPermRelKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BS_UserPermRel
     * @date 2021-11-18 12:08:30
     */
    int insert(UserPermRelKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BS_UserPermRel
     * @date 2021-11-18 12:08:30
     */
    int insertSelective(UserPermRelKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BS_UserPermRel
     * @date 2021-11-18 12:08:30
     */
    List<UserPermRelKey> selectByExample(UserPermRelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BS_UserPermRel
     * @date 2021-11-18 12:08:30
     */
    int updateByExampleSelective(@Param("record") UserPermRelKey record, @Param("example") UserPermRelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BS_UserPermRel
     * @date 2021-11-18 12:08:30
     */
    int updateByExample(@Param("record") UserPermRelKey record, @Param("example") UserPermRelExample example);

    /**
     * 这是Mybatis Generator拓展插件生成的方法(请勿删除).
     * This method corresponds to the database table BS_UserPermRel
     *
     * @mbg.generated
     * @author hewei
     */
    int batchInsert(@Param("list") List<UserPermRelKey> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BS_UserPermRel
     * @date 2021-11-18 12:08:30
     */
    int batchUpdate(@Param("recordList") List<UserPermRelKey> recordList);
}