/**
 * copyright (c) 2020 Kuta Service Framework
 * @author: mybatis generator
 */
package com.kuta.data.mysql.dao;

import com.kuta.data.mysql.dao.extend.UserMapperBase;
import com.kuta.data.mysql.pojo.User;
import com.kuta.data.mysql.pojo.UserExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserMapper extends UserMapperBase {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BS_User
     * @date 2021-12-28 00:51:29
     */
    long countByExample(UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BS_User
     * @date 2021-12-28 00:51:29
     */
    int deleteByExample(UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BS_User
     * @date 2021-12-28 00:51:29
     */
    int deleteByPrimaryKey(Integer uid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BS_User
     * @date 2021-12-28 00:51:29
     */
    int insert(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BS_User
     * @date 2021-12-28 00:51:29
     */
    int insertSelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BS_User
     * @date 2021-12-28 00:51:29
     */
    List<User> selectByExample(UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BS_User
     * @date 2021-12-28 00:51:29
     */
    User selectByPrimaryKey(Integer uid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BS_User
     * @date 2021-12-28 00:51:29
     */
    int updateByExampleSelective(@Param("record") User record, @Param("example") UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BS_User
     * @date 2021-12-28 00:51:29
     */
    int updateByExample(@Param("record") User record, @Param("example") UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BS_User
     * @date 2021-12-28 00:51:29
     */
    int updateByPrimaryKeySelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BS_User
     * @date 2021-12-28 00:51:29
     */
    int updateByPrimaryKey(User record);

    /**
     * 这是Mybatis Generator拓展插件生成的方法(请勿删除).
     * This method corresponds to the database table BS_User
     *
     * @mbg.generated
     * @author hewei
     */
    int batchInsert(@Param("list") List<User> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BS_User
     * @date 2021-12-28 00:51:29
     */
    int updateWithOptimisticLock(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BS_User
     * @date 2021-12-28 00:51:29
     */
    int batchUpdate(@Param("recordList") List<User> recordList);
}