/**
 * copyright (c) 2020 Kuta Service Framework
 * @author: mybatis generator
 */
package com.kuta.data.mysql.pojo;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class PermissionExample {
    /**
     * @date 2021-11-18 12:08:30
     */
    protected String orderByClause;

    /**
     * @date 2021-11-18 12:08:30
     */
    protected boolean distinct;

    /**
     * @date 2021-11-18 12:08:30
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BS_Permission
     * @date 2021-11-18 12:08:30
     */
    public PermissionExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BS_Permission
     * @date 2021-11-18 12:08:30
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BS_Permission
     * @date 2021-11-18 12:08:30
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BS_Permission
     * @date 2021-11-18 12:08:30
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BS_Permission
     * @date 2021-11-18 12:08:30
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BS_Permission
     * @date 2021-11-18 12:08:30
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BS_Permission
     * @date 2021-11-18 12:08:30
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BS_Permission
     * @date 2021-11-18 12:08:30
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BS_Permission
     * @date 2021-11-18 12:08:30
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BS_Permission
     * @date 2021-11-18 12:08:30
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BS_Permission
     * @date 2021-11-18 12:08:30
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * Permission
     * BS_Permission
     * @date 2021-11-18 12:08:30
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andPidIsNull() {
            addCriterion("`pid` is null");
            return (Criteria) this;
        }

        public Criteria andPidIsNotNull() {
            addCriterion("`pid` is not null");
            return (Criteria) this;
        }

        public Criteria andPidEqualTo(Integer value) {
            addCriterion("`pid` =", value, "pid");
            return (Criteria) this;
        }

        public Criteria andPidNotEqualTo(Integer value) {
            addCriterion("`pid` <>", value, "pid");
            return (Criteria) this;
        }

        public Criteria andPidGreaterThan(Integer value) {
            addCriterion("`pid` >", value, "pid");
            return (Criteria) this;
        }

        public Criteria andPidGreaterThanOrEqualTo(Integer value) {
            addCriterion("`pid` >=", value, "pid");
            return (Criteria) this;
        }

        public Criteria andPidLessThan(Integer value) {
            addCriterion("`pid` <", value, "pid");
            return (Criteria) this;
        }

        public Criteria andPidLessThanOrEqualTo(Integer value) {
            addCriterion("`pid` <=", value, "pid");
            return (Criteria) this;
        }

        public Criteria andPidIn(List<Integer> values) {
            addCriterion("`pid` in", values, "pid");
            return (Criteria) this;
        }

        public Criteria andPidNotIn(List<Integer> values) {
            addCriterion("`pid` not in", values, "pid");
            return (Criteria) this;
        }

        public Criteria andPidBetween(Integer value1, Integer value2) {
            addCriterion("`pid` between", value1, value2, "pid");
            return (Criteria) this;
        }

        public Criteria andPidNotBetween(Integer value1, Integer value2) {
            addCriterion("`pid` not between", value1, value2, "pid");
            return (Criteria) this;
        }

        public Criteria andNameIsNull() {
            addCriterion("`name` is null");
            return (Criteria) this;
        }

        public Criteria andNameIsNotNull() {
            addCriterion("`name` is not null");
            return (Criteria) this;
        }

        public Criteria andNameEqualTo(String value) {
            addCriterion("`name` =", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotEqualTo(String value) {
            addCriterion("`name` <>", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThan(String value) {
            addCriterion("`name` >", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThanOrEqualTo(String value) {
            addCriterion("`name` >=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThan(String value) {
            addCriterion("`name` <", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThanOrEqualTo(String value) {
            addCriterion("`name` <=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLike(String value) {
            addCriterion("`name` like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotLike(String value) {
            addCriterion("`name` not like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameIn(List<String> values) {
            addCriterion("`name` in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotIn(List<String> values) {
            addCriterion("`name` not in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameBetween(String value1, String value2) {
            addCriterion("`name` between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotBetween(String value1, String value2) {
            addCriterion("`name` not between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andAliasIsNull() {
            addCriterion("`alias` is null");
            return (Criteria) this;
        }

        public Criteria andAliasIsNotNull() {
            addCriterion("`alias` is not null");
            return (Criteria) this;
        }

        public Criteria andAliasEqualTo(String value) {
            addCriterion("`alias` =", value, "alias");
            return (Criteria) this;
        }

        public Criteria andAliasNotEqualTo(String value) {
            addCriterion("`alias` <>", value, "alias");
            return (Criteria) this;
        }

        public Criteria andAliasGreaterThan(String value) {
            addCriterion("`alias` >", value, "alias");
            return (Criteria) this;
        }

        public Criteria andAliasGreaterThanOrEqualTo(String value) {
            addCriterion("`alias` >=", value, "alias");
            return (Criteria) this;
        }

        public Criteria andAliasLessThan(String value) {
            addCriterion("`alias` <", value, "alias");
            return (Criteria) this;
        }

        public Criteria andAliasLessThanOrEqualTo(String value) {
            addCriterion("`alias` <=", value, "alias");
            return (Criteria) this;
        }

        public Criteria andAliasLike(String value) {
            addCriterion("`alias` like", value, "alias");
            return (Criteria) this;
        }

        public Criteria andAliasNotLike(String value) {
            addCriterion("`alias` not like", value, "alias");
            return (Criteria) this;
        }

        public Criteria andAliasIn(List<String> values) {
            addCriterion("`alias` in", values, "alias");
            return (Criteria) this;
        }

        public Criteria andAliasNotIn(List<String> values) {
            addCriterion("`alias` not in", values, "alias");
            return (Criteria) this;
        }

        public Criteria andAliasBetween(String value1, String value2) {
            addCriterion("`alias` between", value1, value2, "alias");
            return (Criteria) this;
        }

        public Criteria andAliasNotBetween(String value1, String value2) {
            addCriterion("`alias` not between", value1, value2, "alias");
            return (Criteria) this;
        }

        public Criteria andDescIsNull() {
            addCriterion("`desc` is null");
            return (Criteria) this;
        }

        public Criteria andDescIsNotNull() {
            addCriterion("`desc` is not null");
            return (Criteria) this;
        }

        public Criteria andDescEqualTo(String value) {
            addCriterion("`desc` =", value, "desc");
            return (Criteria) this;
        }

        public Criteria andDescNotEqualTo(String value) {
            addCriterion("`desc` <>", value, "desc");
            return (Criteria) this;
        }

        public Criteria andDescGreaterThan(String value) {
            addCriterion("`desc` >", value, "desc");
            return (Criteria) this;
        }

        public Criteria andDescGreaterThanOrEqualTo(String value) {
            addCriterion("`desc` >=", value, "desc");
            return (Criteria) this;
        }

        public Criteria andDescLessThan(String value) {
            addCriterion("`desc` <", value, "desc");
            return (Criteria) this;
        }

        public Criteria andDescLessThanOrEqualTo(String value) {
            addCriterion("`desc` <=", value, "desc");
            return (Criteria) this;
        }

        public Criteria andDescLike(String value) {
            addCriterion("`desc` like", value, "desc");
            return (Criteria) this;
        }

        public Criteria andDescNotLike(String value) {
            addCriterion("`desc` not like", value, "desc");
            return (Criteria) this;
        }

        public Criteria andDescIn(List<String> values) {
            addCriterion("`desc` in", values, "desc");
            return (Criteria) this;
        }

        public Criteria andDescNotIn(List<String> values) {
            addCriterion("`desc` not in", values, "desc");
            return (Criteria) this;
        }

        public Criteria andDescBetween(String value1, String value2) {
            addCriterion("`desc` between", value1, value2, "desc");
            return (Criteria) this;
        }

        public Criteria andDescNotBetween(String value1, String value2) {
            addCriterion("`desc` not between", value1, value2, "desc");
            return (Criteria) this;
        }

        public Criteria andParentRidIsNull() {
            addCriterion("`parent_rid` is null");
            return (Criteria) this;
        }

        public Criteria andParentRidIsNotNull() {
            addCriterion("`parent_rid` is not null");
            return (Criteria) this;
        }

        public Criteria andParentRidEqualTo(Integer value) {
            addCriterion("`parent_rid` =", value, "parentRid");
            return (Criteria) this;
        }

        public Criteria andParentRidNotEqualTo(Integer value) {
            addCriterion("`parent_rid` <>", value, "parentRid");
            return (Criteria) this;
        }

        public Criteria andParentRidGreaterThan(Integer value) {
            addCriterion("`parent_rid` >", value, "parentRid");
            return (Criteria) this;
        }

        public Criteria andParentRidGreaterThanOrEqualTo(Integer value) {
            addCriterion("`parent_rid` >=", value, "parentRid");
            return (Criteria) this;
        }

        public Criteria andParentRidLessThan(Integer value) {
            addCriterion("`parent_rid` <", value, "parentRid");
            return (Criteria) this;
        }

        public Criteria andParentRidLessThanOrEqualTo(Integer value) {
            addCriterion("`parent_rid` <=", value, "parentRid");
            return (Criteria) this;
        }

        public Criteria andParentRidIn(List<Integer> values) {
            addCriterion("`parent_rid` in", values, "parentRid");
            return (Criteria) this;
        }

        public Criteria andParentRidNotIn(List<Integer> values) {
            addCriterion("`parent_rid` not in", values, "parentRid");
            return (Criteria) this;
        }

        public Criteria andParentRidBetween(Integer value1, Integer value2) {
            addCriterion("`parent_rid` between", value1, value2, "parentRid");
            return (Criteria) this;
        }

        public Criteria andParentRidNotBetween(Integer value1, Integer value2) {
            addCriterion("`parent_rid` not between", value1, value2, "parentRid");
            return (Criteria) this;
        }

        public Criteria andLevelIsNull() {
            addCriterion("`level` is null");
            return (Criteria) this;
        }

        public Criteria andLevelIsNotNull() {
            addCriterion("`level` is not null");
            return (Criteria) this;
        }

        public Criteria andLevelEqualTo(String value) {
            addCriterion("`level` =", value, "level");
            return (Criteria) this;
        }

        public Criteria andLevelNotEqualTo(String value) {
            addCriterion("`level` <>", value, "level");
            return (Criteria) this;
        }

        public Criteria andLevelGreaterThan(String value) {
            addCriterion("`level` >", value, "level");
            return (Criteria) this;
        }

        public Criteria andLevelGreaterThanOrEqualTo(String value) {
            addCriterion("`level` >=", value, "level");
            return (Criteria) this;
        }

        public Criteria andLevelLessThan(String value) {
            addCriterion("`level` <", value, "level");
            return (Criteria) this;
        }

        public Criteria andLevelLessThanOrEqualTo(String value) {
            addCriterion("`level` <=", value, "level");
            return (Criteria) this;
        }

        public Criteria andLevelLike(String value) {
            addCriterion("`level` like", value, "level");
            return (Criteria) this;
        }

        public Criteria andLevelNotLike(String value) {
            addCriterion("`level` not like", value, "level");
            return (Criteria) this;
        }

        public Criteria andLevelIn(List<String> values) {
            addCriterion("`level` in", values, "level");
            return (Criteria) this;
        }

        public Criteria andLevelNotIn(List<String> values) {
            addCriterion("`level` not in", values, "level");
            return (Criteria) this;
        }

        public Criteria andLevelBetween(String value1, String value2) {
            addCriterion("`level` between", value1, value2, "level");
            return (Criteria) this;
        }

        public Criteria andLevelNotBetween(String value1, String value2) {
            addCriterion("`level` not between", value1, value2, "level");
            return (Criteria) this;
        }

        public Criteria andDeepIsNull() {
            addCriterion("`deep` is null");
            return (Criteria) this;
        }

        public Criteria andDeepIsNotNull() {
            addCriterion("`deep` is not null");
            return (Criteria) this;
        }

        public Criteria andDeepEqualTo(Byte value) {
            addCriterion("`deep` =", value, "deep");
            return (Criteria) this;
        }

        public Criteria andDeepNotEqualTo(Byte value) {
            addCriterion("`deep` <>", value, "deep");
            return (Criteria) this;
        }

        public Criteria andDeepGreaterThan(Byte value) {
            addCriterion("`deep` >", value, "deep");
            return (Criteria) this;
        }

        public Criteria andDeepGreaterThanOrEqualTo(Byte value) {
            addCriterion("`deep` >=", value, "deep");
            return (Criteria) this;
        }

        public Criteria andDeepLessThan(Byte value) {
            addCriterion("`deep` <", value, "deep");
            return (Criteria) this;
        }

        public Criteria andDeepLessThanOrEqualTo(Byte value) {
            addCriterion("`deep` <=", value, "deep");
            return (Criteria) this;
        }

        public Criteria andDeepIn(List<Byte> values) {
            addCriterion("`deep` in", values, "deep");
            return (Criteria) this;
        }

        public Criteria andDeepNotIn(List<Byte> values) {
            addCriterion("`deep` not in", values, "deep");
            return (Criteria) this;
        }

        public Criteria andDeepBetween(Byte value1, Byte value2) {
            addCriterion("`deep` between", value1, value2, "deep");
            return (Criteria) this;
        }

        public Criteria andDeepNotBetween(Byte value1, Byte value2) {
            addCriterion("`deep` not between", value1, value2, "deep");
            return (Criteria) this;
        }

        public Criteria andIdxIsNull() {
            addCriterion("`idx` is null");
            return (Criteria) this;
        }

        public Criteria andIdxIsNotNull() {
            addCriterion("`idx` is not null");
            return (Criteria) this;
        }

        public Criteria andIdxEqualTo(Short value) {
            addCriterion("`idx` =", value, "idx");
            return (Criteria) this;
        }

        public Criteria andIdxNotEqualTo(Short value) {
            addCriterion("`idx` <>", value, "idx");
            return (Criteria) this;
        }

        public Criteria andIdxGreaterThan(Short value) {
            addCriterion("`idx` >", value, "idx");
            return (Criteria) this;
        }

        public Criteria andIdxGreaterThanOrEqualTo(Short value) {
            addCriterion("`idx` >=", value, "idx");
            return (Criteria) this;
        }

        public Criteria andIdxLessThan(Short value) {
            addCriterion("`idx` <", value, "idx");
            return (Criteria) this;
        }

        public Criteria andIdxLessThanOrEqualTo(Short value) {
            addCriterion("`idx` <=", value, "idx");
            return (Criteria) this;
        }

        public Criteria andIdxIn(List<Short> values) {
            addCriterion("`idx` in", values, "idx");
            return (Criteria) this;
        }

        public Criteria andIdxNotIn(List<Short> values) {
            addCriterion("`idx` not in", values, "idx");
            return (Criteria) this;
        }

        public Criteria andIdxBetween(Short value1, Short value2) {
            addCriterion("`idx` between", value1, value2, "idx");
            return (Criteria) this;
        }

        public Criteria andIdxNotBetween(Short value1, Short value2) {
            addCriterion("`idx` not between", value1, value2, "idx");
            return (Criteria) this;
        }

        public Criteria andClassifyIsNull() {
            addCriterion("`classify` is null");
            return (Criteria) this;
        }

        public Criteria andClassifyIsNotNull() {
            addCriterion("`classify` is not null");
            return (Criteria) this;
        }

        public Criteria andClassifyEqualTo(Short value) {
            addCriterion("`classify` =", value, "classify");
            return (Criteria) this;
        }

        public Criteria andClassifyNotEqualTo(Short value) {
            addCriterion("`classify` <>", value, "classify");
            return (Criteria) this;
        }

        public Criteria andClassifyGreaterThan(Short value) {
            addCriterion("`classify` >", value, "classify");
            return (Criteria) this;
        }

        public Criteria andClassifyGreaterThanOrEqualTo(Short value) {
            addCriterion("`classify` >=", value, "classify");
            return (Criteria) this;
        }

        public Criteria andClassifyLessThan(Short value) {
            addCriterion("`classify` <", value, "classify");
            return (Criteria) this;
        }

        public Criteria andClassifyLessThanOrEqualTo(Short value) {
            addCriterion("`classify` <=", value, "classify");
            return (Criteria) this;
        }

        public Criteria andClassifyIn(List<Short> values) {
            addCriterion("`classify` in", values, "classify");
            return (Criteria) this;
        }

        public Criteria andClassifyNotIn(List<Short> values) {
            addCriterion("`classify` not in", values, "classify");
            return (Criteria) this;
        }

        public Criteria andClassifyBetween(Short value1, Short value2) {
            addCriterion("`classify` between", value1, value2, "classify");
            return (Criteria) this;
        }

        public Criteria andClassifyNotBetween(Short value1, Short value2) {
            addCriterion("`classify` not between", value1, value2, "classify");
            return (Criteria) this;
        }

        public Criteria andCreatedIsNull() {
            addCriterion("`created` is null");
            return (Criteria) this;
        }

        public Criteria andCreatedIsNotNull() {
            addCriterion("`created` is not null");
            return (Criteria) this;
        }

        public Criteria andCreatedEqualTo(Date value) {
            addCriterion("`created` =", value, "created");
            return (Criteria) this;
        }

        public Criteria andCreatedNotEqualTo(Date value) {
            addCriterion("`created` <>", value, "created");
            return (Criteria) this;
        }

        public Criteria andCreatedGreaterThan(Date value) {
            addCriterion("`created` >", value, "created");
            return (Criteria) this;
        }

        public Criteria andCreatedGreaterThanOrEqualTo(Date value) {
            addCriterion("`created` >=", value, "created");
            return (Criteria) this;
        }

        public Criteria andCreatedLessThan(Date value) {
            addCriterion("`created` <", value, "created");
            return (Criteria) this;
        }

        public Criteria andCreatedLessThanOrEqualTo(Date value) {
            addCriterion("`created` <=", value, "created");
            return (Criteria) this;
        }

        public Criteria andCreatedIn(List<Date> values) {
            addCriterion("`created` in", values, "created");
            return (Criteria) this;
        }

        public Criteria andCreatedNotIn(List<Date> values) {
            addCriterion("`created` not in", values, "created");
            return (Criteria) this;
        }

        public Criteria andCreatedBetween(Date value1, Date value2) {
            addCriterion("`created` between", value1, value2, "created");
            return (Criteria) this;
        }

        public Criteria andCreatedNotBetween(Date value1, Date value2) {
            addCriterion("`created` not between", value1, value2, "created");
            return (Criteria) this;
        }

        public Criteria andPidEqualTo(boolean condition, Integer value) {
            if (condition) {
                addCriterion("`pid` =", value, "pid");
            }
            return (Criteria) this;
        }

        public Criteria andPidGreaterThanOrEqualTo(boolean condition, Integer value) {
            if (condition) {
                addCriterion("`pid` >=", value, "pid");
            }
            return (Criteria) this;
        }

        public Criteria andPidIn(boolean condition, List<Integer> value) {
            if (condition) {
                addCriterion("`pid` in", value, "pid");
            }
            return (Criteria) this;
        }

        public Criteria andNameEqualTo(boolean condition, String value) {
            if (condition) {
                addCriterion("`name` =", value, "name");
            }
            return (Criteria) this;
        }

        public Criteria andNameGreaterThanOrEqualTo(boolean condition, String value) {
            if (condition) {
                addCriterion("`name` >=", value, "name");
            }
            return (Criteria) this;
        }

        public Criteria andNameIn(boolean condition, List<String> value) {
            if (condition) {
                addCriterion("`name` in", value, "name");
            }
            return (Criteria) this;
        }

        public Criteria andAliasEqualTo(boolean condition, String value) {
            if (condition) {
                addCriterion("`alias` =", value, "alias");
            }
            return (Criteria) this;
        }

        public Criteria andAliasGreaterThanOrEqualTo(boolean condition, String value) {
            if (condition) {
                addCriterion("`alias` >=", value, "alias");
            }
            return (Criteria) this;
        }

        public Criteria andAliasIn(boolean condition, List<String> value) {
            if (condition) {
                addCriterion("`alias` in", value, "alias");
            }
            return (Criteria) this;
        }

        public Criteria andDescEqualTo(boolean condition, String value) {
            if (condition) {
                addCriterion("`desc` =", value, "desc");
            }
            return (Criteria) this;
        }

        public Criteria andDescGreaterThanOrEqualTo(boolean condition, String value) {
            if (condition) {
                addCriterion("`desc` >=", value, "desc");
            }
            return (Criteria) this;
        }

        public Criteria andDescIn(boolean condition, List<String> value) {
            if (condition) {
                addCriterion("`desc` in", value, "desc");
            }
            return (Criteria) this;
        }

        public Criteria andParentRidEqualTo(boolean condition, Integer value) {
            if (condition) {
                addCriterion("`parent_rid` =", value, "parentRid");
            }
            return (Criteria) this;
        }

        public Criteria andParentRidGreaterThanOrEqualTo(boolean condition, Integer value) {
            if (condition) {
                addCriterion("`parent_rid` >=", value, "parentRid");
            }
            return (Criteria) this;
        }

        public Criteria andParentRidIn(boolean condition, List<Integer> value) {
            if (condition) {
                addCriterion("`parent_rid` in", value, "parentRid");
            }
            return (Criteria) this;
        }

        public Criteria andLevelEqualTo(boolean condition, String value) {
            if (condition) {
                addCriterion("`level` =", value, "level");
            }
            return (Criteria) this;
        }

        public Criteria andLevelGreaterThanOrEqualTo(boolean condition, String value) {
            if (condition) {
                addCriterion("`level` >=", value, "level");
            }
            return (Criteria) this;
        }

        public Criteria andLevelIn(boolean condition, List<String> value) {
            if (condition) {
                addCriterion("`level` in", value, "level");
            }
            return (Criteria) this;
        }

        public Criteria andDeepEqualTo(boolean condition, Byte value) {
            if (condition) {
                addCriterion("`deep` =", value, "deep");
            }
            return (Criteria) this;
        }

        public Criteria andDeepGreaterThanOrEqualTo(boolean condition, Byte value) {
            if (condition) {
                addCriterion("`deep` >=", value, "deep");
            }
            return (Criteria) this;
        }

        public Criteria andDeepIn(boolean condition, List<Byte> value) {
            if (condition) {
                addCriterion("`deep` in", value, "deep");
            }
            return (Criteria) this;
        }

        public Criteria andIdxEqualTo(boolean condition, Short value) {
            if (condition) {
                addCriterion("`idx` =", value, "idx");
            }
            return (Criteria) this;
        }

        public Criteria andIdxGreaterThanOrEqualTo(boolean condition, Short value) {
            if (condition) {
                addCriterion("`idx` >=", value, "idx");
            }
            return (Criteria) this;
        }

        public Criteria andIdxIn(boolean condition, List<Short> value) {
            if (condition) {
                addCriterion("`idx` in", value, "idx");
            }
            return (Criteria) this;
        }

        public Criteria andClassifyEqualTo(boolean condition, Short value) {
            if (condition) {
                addCriterion("`classify` =", value, "classify");
            }
            return (Criteria) this;
        }

        public Criteria andClassifyGreaterThanOrEqualTo(boolean condition, Short value) {
            if (condition) {
                addCriterion("`classify` >=", value, "classify");
            }
            return (Criteria) this;
        }

        public Criteria andClassifyIn(boolean condition, List<Short> value) {
            if (condition) {
                addCriterion("`classify` in", value, "classify");
            }
            return (Criteria) this;
        }

        public Criteria andCreatedEqualTo(boolean condition, Date value) {
            if (condition) {
                addCriterion("`created` =", value, "created");
            }
            return (Criteria) this;
        }

        public Criteria andCreatedGreaterThanOrEqualTo(boolean condition, Date value) {
            if (condition) {
                addCriterion("`created` >=", value, "created");
            }
            return (Criteria) this;
        }

        public Criteria andCreatedIn(boolean condition, List<Date> value) {
            if (condition) {
                addCriterion("`created` in", value, "created");
            }
            return (Criteria) this;
        }
    }

    /**
     * null<p/>
     * BS_Permission
     * @date 2021-11-18 12:08:30
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * Permission
     * BS_Permission
     * @date 2021-11-18 12:08:30
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}