/**
 * copyright (c) 2020 Kuta Service Framework
 * @author: mybatis generator
 */
package com.kuta.data.mysql.pojo;

import java.io.Serializable;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table BS_Plugin_Org_Param
 * @date 2021-11-18 12:08:30
 */
public class PluginOrganizationParam extends PluginOrganizationParamKey implements Serializable {
    /**
     * @desc 参数值
     * @jdbcType VARCHAR
     * @author mybatis generator
     * @date 2021-11-18 12:08:30
     */
    private String val;

    /**
     * @date 2021-11-18 12:08:30
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BS_Plugin_Org_Param
     * @date 2021-11-18 12:08:30
     */
    public PluginOrganizationParam(Integer poid, Integer pptid, String val) {
        super(poid, pptid);
        this.val = val;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BS_Plugin_Org_Param
     * @date 2021-11-18 12:08:30
     */
    public PluginOrganizationParam() {
        super();
    }

    /**
     * @return val : 参数值
     */
    public String getVal() {
        return val;
    }

    /**
     * @param val : 参数值
     */
    public void setVal(String val) {
        this.val = val == null ? null : val.trim();
    }
}