/**
 * copyright (c) 2020 Kuta Service Framework
 * @author: mybatis generator
 */
package com.kuta.data.mysql.pojo;

import java.util.ArrayList;
import java.util.List;

public class PluginHttpHeaderExample {
    /**
     * @date 2021-07-15 12:55:28
     */
    protected String orderByClause;

    /**
     * @date 2021-07-15 12:55:28
     */
    protected boolean distinct;

    /**
     * @date 2021-07-15 12:55:28
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BS_Plugin_Http_Header
     * @date 2021-07-15 12:55:28
     */
    public PluginHttpHeaderExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BS_Plugin_Http_Header
     * @date 2021-07-15 12:55:28
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BS_Plugin_Http_Header
     * @date 2021-07-15 12:55:28
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BS_Plugin_Http_Header
     * @date 2021-07-15 12:55:28
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BS_Plugin_Http_Header
     * @date 2021-07-15 12:55:28
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BS_Plugin_Http_Header
     * @date 2021-07-15 12:55:28
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BS_Plugin_Http_Header
     * @date 2021-07-15 12:55:28
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BS_Plugin_Http_Header
     * @date 2021-07-15 12:55:28
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BS_Plugin_Http_Header
     * @date 2021-07-15 12:55:28
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BS_Plugin_Http_Header
     * @date 2021-07-15 12:55:28
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BS_Plugin_Http_Header
     * @date 2021-07-15 12:55:28
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * PluginHttpHeader
     * BS_Plugin_Http_Header
     * @date 2021-07-15 12:55:28
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andPhhidIsNull() {
            addCriterion("`phhid` is null");
            return (Criteria) this;
        }

        public Criteria andPhhidIsNotNull() {
            addCriterion("`phhid` is not null");
            return (Criteria) this;
        }

        public Criteria andPhhidEqualTo(Integer value) {
            addCriterion("`phhid` =", value, "phhid");
            return (Criteria) this;
        }

        public Criteria andPhhidNotEqualTo(Integer value) {
            addCriterion("`phhid` <>", value, "phhid");
            return (Criteria) this;
        }

        public Criteria andPhhidGreaterThan(Integer value) {
            addCriterion("`phhid` >", value, "phhid");
            return (Criteria) this;
        }

        public Criteria andPhhidGreaterThanOrEqualTo(Integer value) {
            addCriterion("`phhid` >=", value, "phhid");
            return (Criteria) this;
        }

        public Criteria andPhhidLessThan(Integer value) {
            addCriterion("`phhid` <", value, "phhid");
            return (Criteria) this;
        }

        public Criteria andPhhidLessThanOrEqualTo(Integer value) {
            addCriterion("`phhid` <=", value, "phhid");
            return (Criteria) this;
        }

        public Criteria andPhhidIn(List<Integer> values) {
            addCriterion("`phhid` in", values, "phhid");
            return (Criteria) this;
        }

        public Criteria andPhhidNotIn(List<Integer> values) {
            addCriterion("`phhid` not in", values, "phhid");
            return (Criteria) this;
        }

        public Criteria andPhhidBetween(Integer value1, Integer value2) {
            addCriterion("`phhid` between", value1, value2, "phhid");
            return (Criteria) this;
        }

        public Criteria andPhhidNotBetween(Integer value1, Integer value2) {
            addCriterion("`phhid` not between", value1, value2, "phhid");
            return (Criteria) this;
        }

        public Criteria andKeyIsNull() {
            addCriterion("`key` is null");
            return (Criteria) this;
        }

        public Criteria andKeyIsNotNull() {
            addCriterion("`key` is not null");
            return (Criteria) this;
        }

        public Criteria andKeyEqualTo(String value) {
            addCriterion("`key` =", value, "key");
            return (Criteria) this;
        }

        public Criteria andKeyNotEqualTo(String value) {
            addCriterion("`key` <>", value, "key");
            return (Criteria) this;
        }

        public Criteria andKeyGreaterThan(String value) {
            addCriterion("`key` >", value, "key");
            return (Criteria) this;
        }

        public Criteria andKeyGreaterThanOrEqualTo(String value) {
            addCriterion("`key` >=", value, "key");
            return (Criteria) this;
        }

        public Criteria andKeyLessThan(String value) {
            addCriterion("`key` <", value, "key");
            return (Criteria) this;
        }

        public Criteria andKeyLessThanOrEqualTo(String value) {
            addCriterion("`key` <=", value, "key");
            return (Criteria) this;
        }

        public Criteria andKeyLike(String value) {
            addCriterion("`key` like", value, "key");
            return (Criteria) this;
        }

        public Criteria andKeyNotLike(String value) {
            addCriterion("`key` not like", value, "key");
            return (Criteria) this;
        }

        public Criteria andKeyIn(List<String> values) {
            addCriterion("`key` in", values, "key");
            return (Criteria) this;
        }

        public Criteria andKeyNotIn(List<String> values) {
            addCriterion("`key` not in", values, "key");
            return (Criteria) this;
        }

        public Criteria andKeyBetween(String value1, String value2) {
            addCriterion("`key` between", value1, value2, "key");
            return (Criteria) this;
        }

        public Criteria andKeyNotBetween(String value1, String value2) {
            addCriterion("`key` not between", value1, value2, "key");
            return (Criteria) this;
        }

        public Criteria andValueIsNull() {
            addCriterion("`value` is null");
            return (Criteria) this;
        }

        public Criteria andValueIsNotNull() {
            addCriterion("`value` is not null");
            return (Criteria) this;
        }

        public Criteria andValueEqualTo(String value) {
            addCriterion("`value` =", value, "value");
            return (Criteria) this;
        }

        public Criteria andValueNotEqualTo(String value) {
            addCriterion("`value` <>", value, "value");
            return (Criteria) this;
        }

        public Criteria andValueGreaterThan(String value) {
            addCriterion("`value` >", value, "value");
            return (Criteria) this;
        }

        public Criteria andValueGreaterThanOrEqualTo(String value) {
            addCriterion("`value` >=", value, "value");
            return (Criteria) this;
        }

        public Criteria andValueLessThan(String value) {
            addCriterion("`value` <", value, "value");
            return (Criteria) this;
        }

        public Criteria andValueLessThanOrEqualTo(String value) {
            addCriterion("`value` <=", value, "value");
            return (Criteria) this;
        }

        public Criteria andValueLike(String value) {
            addCriterion("`value` like", value, "value");
            return (Criteria) this;
        }

        public Criteria andValueNotLike(String value) {
            addCriterion("`value` not like", value, "value");
            return (Criteria) this;
        }

        public Criteria andValueIn(List<String> values) {
            addCriterion("`value` in", values, "value");
            return (Criteria) this;
        }

        public Criteria andValueNotIn(List<String> values) {
            addCriterion("`value` not in", values, "value");
            return (Criteria) this;
        }

        public Criteria andValueBetween(String value1, String value2) {
            addCriterion("`value` between", value1, value2, "value");
            return (Criteria) this;
        }

        public Criteria andValueNotBetween(String value1, String value2) {
            addCriterion("`value` not between", value1, value2, "value");
            return (Criteria) this;
        }

        public Criteria andPhridIsNull() {
            addCriterion("`phrid` is null");
            return (Criteria) this;
        }

        public Criteria andPhridIsNotNull() {
            addCriterion("`phrid` is not null");
            return (Criteria) this;
        }

        public Criteria andPhridEqualTo(Integer value) {
            addCriterion("`phrid` =", value, "phrid");
            return (Criteria) this;
        }

        public Criteria andPhridNotEqualTo(Integer value) {
            addCriterion("`phrid` <>", value, "phrid");
            return (Criteria) this;
        }

        public Criteria andPhridGreaterThan(Integer value) {
            addCriterion("`phrid` >", value, "phrid");
            return (Criteria) this;
        }

        public Criteria andPhridGreaterThanOrEqualTo(Integer value) {
            addCriterion("`phrid` >=", value, "phrid");
            return (Criteria) this;
        }

        public Criteria andPhridLessThan(Integer value) {
            addCriterion("`phrid` <", value, "phrid");
            return (Criteria) this;
        }

        public Criteria andPhridLessThanOrEqualTo(Integer value) {
            addCriterion("`phrid` <=", value, "phrid");
            return (Criteria) this;
        }

        public Criteria andPhridIn(List<Integer> values) {
            addCriterion("`phrid` in", values, "phrid");
            return (Criteria) this;
        }

        public Criteria andPhridNotIn(List<Integer> values) {
            addCriterion("`phrid` not in", values, "phrid");
            return (Criteria) this;
        }

        public Criteria andPhridBetween(Integer value1, Integer value2) {
            addCriterion("`phrid` between", value1, value2, "phrid");
            return (Criteria) this;
        }

        public Criteria andPhridNotBetween(Integer value1, Integer value2) {
            addCriterion("`phrid` not between", value1, value2, "phrid");
            return (Criteria) this;
        }

        public Criteria andTypeIsNull() {
            addCriterion("`type` is null");
            return (Criteria) this;
        }

        public Criteria andTypeIsNotNull() {
            addCriterion("`type` is not null");
            return (Criteria) this;
        }

        public Criteria andTypeEqualTo(Byte value) {
            addCriterion("`type` =", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotEqualTo(Byte value) {
            addCriterion("`type` <>", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeGreaterThan(Byte value) {
            addCriterion("`type` >", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeGreaterThanOrEqualTo(Byte value) {
            addCriterion("`type` >=", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLessThan(Byte value) {
            addCriterion("`type` <", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLessThanOrEqualTo(Byte value) {
            addCriterion("`type` <=", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeIn(List<Byte> values) {
            addCriterion("`type` in", values, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotIn(List<Byte> values) {
            addCriterion("`type` not in", values, "type");
            return (Criteria) this;
        }

        public Criteria andTypeBetween(Byte value1, Byte value2) {
            addCriterion("`type` between", value1, value2, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotBetween(Byte value1, Byte value2) {
            addCriterion("`type` not between", value1, value2, "type");
            return (Criteria) this;
        }

        public Criteria andPhhidEqualTo(boolean condition, Integer value) {
            if (condition) {
                addCriterion("`phhid` =", value, "phhid");
            }
            return (Criteria) this;
        }

        public Criteria andPhhidGreaterThanOrEqualTo(boolean condition, Integer value) {
            if (condition) {
                addCriterion("`phhid` >=", value, "phhid");
            }
            return (Criteria) this;
        }

        public Criteria andPhhidIn(boolean condition, List<Integer> value) {
            if (condition) {
                addCriterion("`phhid` in", value, "phhid");
            }
            return (Criteria) this;
        }

        public Criteria andKeyEqualTo(boolean condition, String value) {
            if (condition) {
                addCriterion("`key` =", value, "key");
            }
            return (Criteria) this;
        }

        public Criteria andKeyGreaterThanOrEqualTo(boolean condition, String value) {
            if (condition) {
                addCriterion("`key` >=", value, "key");
            }
            return (Criteria) this;
        }

        public Criteria andKeyIn(boolean condition, List<String> value) {
            if (condition) {
                addCriterion("`key` in", value, "key");
            }
            return (Criteria) this;
        }

        public Criteria andValueEqualTo(boolean condition, String value) {
            if (condition) {
                addCriterion("`value` =", value, "value");
            }
            return (Criteria) this;
        }

        public Criteria andValueGreaterThanOrEqualTo(boolean condition, String value) {
            if (condition) {
                addCriterion("`value` >=", value, "value");
            }
            return (Criteria) this;
        }

        public Criteria andValueIn(boolean condition, List<String> value) {
            if (condition) {
                addCriterion("`value` in", value, "value");
            }
            return (Criteria) this;
        }

        public Criteria andPhridEqualTo(boolean condition, Integer value) {
            if (condition) {
                addCriterion("`phrid` =", value, "phrid");
            }
            return (Criteria) this;
        }

        public Criteria andPhridGreaterThanOrEqualTo(boolean condition, Integer value) {
            if (condition) {
                addCriterion("`phrid` >=", value, "phrid");
            }
            return (Criteria) this;
        }

        public Criteria andPhridIn(boolean condition, List<Integer> value) {
            if (condition) {
                addCriterion("`phrid` in", value, "phrid");
            }
            return (Criteria) this;
        }

        public Criteria andTypeEqualTo(boolean condition, Byte value) {
            if (condition) {
                addCriterion("`type` =", value, "type");
            }
            return (Criteria) this;
        }

        public Criteria andTypeGreaterThanOrEqualTo(boolean condition, Byte value) {
            if (condition) {
                addCriterion("`type` >=", value, "type");
            }
            return (Criteria) this;
        }

        public Criteria andTypeIn(boolean condition, List<Byte> value) {
            if (condition) {
                addCriterion("`type` in", value, "type");
            }
            return (Criteria) this;
        }
    }

    /**
     * null<p/>
     * BS_Plugin_Http_Header
     * @date 2021-07-15 12:55:28
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * PluginHttpHeader
     * BS_Plugin_Http_Header
     * @date 2021-07-15 12:55:28
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}