/**
 * copyright (c) 2020 Kuta Service Framework
 * @author: mybatis generator
 */
package com.kuta.data.mysql.pojo;

import com.kuta.base.annotation.PrimaryKey;
import com.kuta.base.database.KutaDBEntity;
import java.io.Serializable;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table BS_Plugin_Http_Header
 * @date 2021-11-18 12:08:30
 */
public class PluginHttpHeader extends KutaDBEntity implements Serializable {
    /**
     * @desc 
     * @jdbcType INTEGER
     * @author mybatis generator
     * @date 2021-11-18 12:08:30
     */
    @PrimaryKey
    private Integer phhid;

    /**
     * @desc 
     * @jdbcType VARCHAR
     * @author mybatis generator
     * @date 2021-11-18 12:08:30
     */
    private String key;

    /**
     * @desc 
     * @jdbcType VARCHAR
     * @author mybatis generator
     * @date 2021-11-18 12:08:30
     */
    private String value;

    /**
     * @desc 请求编号
     * @jdbcType INTEGER
     * @author mybatis generator
     * @date 2021-11-18 12:08:30
     */
    private Integer phrid;

    /**
     * @desc 1:request 2:report
     * @jdbcType TINYINT
     * @author mybatis generator
     * @date 2021-11-18 12:08:30
     */
    private Byte type;

    /**
     * @date 2021-11-18 12:08:30
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BS_Plugin_Http_Header
     * @date 2021-11-18 12:08:30
     */
    public PluginHttpHeader(Integer phhid, String key, String value, Integer phrid, Byte type) {
        this.phhid = phhid;
        this.key = key;
        this.value = value;
        this.phrid = phrid;
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BS_Plugin_Http_Header
     * @date 2021-11-18 12:08:30
     */
    public PluginHttpHeader() {
        super();
    }

    /**
     * @return phhid : 
     */
    public Integer getPhhid() {
        return phhid;
    }

    /**
     * @param phhid : 
     */
    public void setPhhid(Integer phhid) {
        this.phhid = phhid;
    }

    /**
     * @return key : 
     */
    public String getKey() {
        return key;
    }

    /**
     * @param key : 
     */
    public void setKey(String key) {
        this.key = key == null ? null : key.trim();
    }

    /**
     * @return value : 
     */
    public String getValue() {
        return value;
    }

    /**
     * @param value : 
     */
    public void setValue(String value) {
        this.value = value == null ? null : value.trim();
    }

    /**
     * @return phrid : 请求编号
     */
    public Integer getPhrid() {
        return phrid;
    }

    /**
     * @param phrid : 请求编号
     */
    public void setPhrid(Integer phrid) {
        this.phrid = phrid;
    }

    /**
     * @return type : 1:request 2:report
     */
    public Byte getType() {
        return type;
    }

    /**
     * @param type : 1:request 2:report
     */
    public void setType(Byte type) {
        this.type = type;
    }
}