/**
 * copyright (c) 2020 Kuta Service Framework
 * @author: mybatis generator
 */
package com.kuta.data.mysql.pojo;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class PluginExample {
    /**
     * @date 2021-08-22 14:53:49
     */
    protected String orderByClause;

    /**
     * @date 2021-08-22 14:53:49
     */
    protected boolean distinct;

    /**
     * @date 2021-08-22 14:53:49
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BS_Plugin
     * @date 2021-08-22 14:53:49
     */
    public PluginExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BS_Plugin
     * @date 2021-08-22 14:53:49
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BS_Plugin
     * @date 2021-08-22 14:53:49
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BS_Plugin
     * @date 2021-08-22 14:53:49
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BS_Plugin
     * @date 2021-08-22 14:53:49
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BS_Plugin
     * @date 2021-08-22 14:53:49
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BS_Plugin
     * @date 2021-08-22 14:53:49
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BS_Plugin
     * @date 2021-08-22 14:53:49
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BS_Plugin
     * @date 2021-08-22 14:53:49
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BS_Plugin
     * @date 2021-08-22 14:53:49
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BS_Plugin
     * @date 2021-08-22 14:53:49
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * Plugin
     * BS_Plugin
     * @date 2021-08-22 14:53:49
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andPidIsNull() {
            addCriterion("`pid` is null");
            return (Criteria) this;
        }

        public Criteria andPidIsNotNull() {
            addCriterion("`pid` is not null");
            return (Criteria) this;
        }

        public Criteria andPidEqualTo(Integer value) {
            addCriterion("`pid` =", value, "pid");
            return (Criteria) this;
        }

        public Criteria andPidNotEqualTo(Integer value) {
            addCriterion("`pid` <>", value, "pid");
            return (Criteria) this;
        }

        public Criteria andPidGreaterThan(Integer value) {
            addCriterion("`pid` >", value, "pid");
            return (Criteria) this;
        }

        public Criteria andPidGreaterThanOrEqualTo(Integer value) {
            addCriterion("`pid` >=", value, "pid");
            return (Criteria) this;
        }

        public Criteria andPidLessThan(Integer value) {
            addCriterion("`pid` <", value, "pid");
            return (Criteria) this;
        }

        public Criteria andPidLessThanOrEqualTo(Integer value) {
            addCriterion("`pid` <=", value, "pid");
            return (Criteria) this;
        }

        public Criteria andPidIn(List<Integer> values) {
            addCriterion("`pid` in", values, "pid");
            return (Criteria) this;
        }

        public Criteria andPidNotIn(List<Integer> values) {
            addCriterion("`pid` not in", values, "pid");
            return (Criteria) this;
        }

        public Criteria andPidBetween(Integer value1, Integer value2) {
            addCriterion("`pid` between", value1, value2, "pid");
            return (Criteria) this;
        }

        public Criteria andPidNotBetween(Integer value1, Integer value2) {
            addCriterion("`pid` not between", value1, value2, "pid");
            return (Criteria) this;
        }

        public Criteria andNameIsNull() {
            addCriterion("`name` is null");
            return (Criteria) this;
        }

        public Criteria andNameIsNotNull() {
            addCriterion("`name` is not null");
            return (Criteria) this;
        }

        public Criteria andNameEqualTo(String value) {
            addCriterion("`name` =", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotEqualTo(String value) {
            addCriterion("`name` <>", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThan(String value) {
            addCriterion("`name` >", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThanOrEqualTo(String value) {
            addCriterion("`name` >=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThan(String value) {
            addCriterion("`name` <", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThanOrEqualTo(String value) {
            addCriterion("`name` <=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLike(String value) {
            addCriterion("`name` like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotLike(String value) {
            addCriterion("`name` not like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameIn(List<String> values) {
            addCriterion("`name` in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotIn(List<String> values) {
            addCriterion("`name` not in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameBetween(String value1, String value2) {
            addCriterion("`name` between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotBetween(String value1, String value2) {
            addCriterion("`name` not between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andDescIsNull() {
            addCriterion("`desc` is null");
            return (Criteria) this;
        }

        public Criteria andDescIsNotNull() {
            addCriterion("`desc` is not null");
            return (Criteria) this;
        }

        public Criteria andDescEqualTo(String value) {
            addCriterion("`desc` =", value, "desc");
            return (Criteria) this;
        }

        public Criteria andDescNotEqualTo(String value) {
            addCriterion("`desc` <>", value, "desc");
            return (Criteria) this;
        }

        public Criteria andDescGreaterThan(String value) {
            addCriterion("`desc` >", value, "desc");
            return (Criteria) this;
        }

        public Criteria andDescGreaterThanOrEqualTo(String value) {
            addCriterion("`desc` >=", value, "desc");
            return (Criteria) this;
        }

        public Criteria andDescLessThan(String value) {
            addCriterion("`desc` <", value, "desc");
            return (Criteria) this;
        }

        public Criteria andDescLessThanOrEqualTo(String value) {
            addCriterion("`desc` <=", value, "desc");
            return (Criteria) this;
        }

        public Criteria andDescLike(String value) {
            addCriterion("`desc` like", value, "desc");
            return (Criteria) this;
        }

        public Criteria andDescNotLike(String value) {
            addCriterion("`desc` not like", value, "desc");
            return (Criteria) this;
        }

        public Criteria andDescIn(List<String> values) {
            addCriterion("`desc` in", values, "desc");
            return (Criteria) this;
        }

        public Criteria andDescNotIn(List<String> values) {
            addCriterion("`desc` not in", values, "desc");
            return (Criteria) this;
        }

        public Criteria andDescBetween(String value1, String value2) {
            addCriterion("`desc` between", value1, value2, "desc");
            return (Criteria) this;
        }

        public Criteria andDescNotBetween(String value1, String value2) {
            addCriterion("`desc` not between", value1, value2, "desc");
            return (Criteria) this;
        }

        public Criteria andCreatedIsNull() {
            addCriterion("`created` is null");
            return (Criteria) this;
        }

        public Criteria andCreatedIsNotNull() {
            addCriterion("`created` is not null");
            return (Criteria) this;
        }

        public Criteria andCreatedEqualTo(Date value) {
            addCriterion("`created` =", value, "created");
            return (Criteria) this;
        }

        public Criteria andCreatedNotEqualTo(Date value) {
            addCriterion("`created` <>", value, "created");
            return (Criteria) this;
        }

        public Criteria andCreatedGreaterThan(Date value) {
            addCriterion("`created` >", value, "created");
            return (Criteria) this;
        }

        public Criteria andCreatedGreaterThanOrEqualTo(Date value) {
            addCriterion("`created` >=", value, "created");
            return (Criteria) this;
        }

        public Criteria andCreatedLessThan(Date value) {
            addCriterion("`created` <", value, "created");
            return (Criteria) this;
        }

        public Criteria andCreatedLessThanOrEqualTo(Date value) {
            addCriterion("`created` <=", value, "created");
            return (Criteria) this;
        }

        public Criteria andCreatedIn(List<Date> values) {
            addCriterion("`created` in", values, "created");
            return (Criteria) this;
        }

        public Criteria andCreatedNotIn(List<Date> values) {
            addCriterion("`created` not in", values, "created");
            return (Criteria) this;
        }

        public Criteria andCreatedBetween(Date value1, Date value2) {
            addCriterion("`created` between", value1, value2, "created");
            return (Criteria) this;
        }

        public Criteria andCreatedNotBetween(Date value1, Date value2) {
            addCriterion("`created` not between", value1, value2, "created");
            return (Criteria) this;
        }

        public Criteria andEnableIsNull() {
            addCriterion("`enable` is null");
            return (Criteria) this;
        }

        public Criteria andEnableIsNotNull() {
            addCriterion("`enable` is not null");
            return (Criteria) this;
        }

        public Criteria andEnableEqualTo(Boolean value) {
            addCriterion("`enable` =", value, "enable");
            return (Criteria) this;
        }

        public Criteria andEnableNotEqualTo(Boolean value) {
            addCriterion("`enable` <>", value, "enable");
            return (Criteria) this;
        }

        public Criteria andEnableGreaterThan(Boolean value) {
            addCriterion("`enable` >", value, "enable");
            return (Criteria) this;
        }

        public Criteria andEnableGreaterThanOrEqualTo(Boolean value) {
            addCriterion("`enable` >=", value, "enable");
            return (Criteria) this;
        }

        public Criteria andEnableLessThan(Boolean value) {
            addCriterion("`enable` <", value, "enable");
            return (Criteria) this;
        }

        public Criteria andEnableLessThanOrEqualTo(Boolean value) {
            addCriterion("`enable` <=", value, "enable");
            return (Criteria) this;
        }

        public Criteria andEnableIn(List<Boolean> values) {
            addCriterion("`enable` in", values, "enable");
            return (Criteria) this;
        }

        public Criteria andEnableNotIn(List<Boolean> values) {
            addCriterion("`enable` not in", values, "enable");
            return (Criteria) this;
        }

        public Criteria andEnableBetween(Boolean value1, Boolean value2) {
            addCriterion("`enable` between", value1, value2, "enable");
            return (Criteria) this;
        }

        public Criteria andEnableNotBetween(Boolean value1, Boolean value2) {
            addCriterion("`enable` not between", value1, value2, "enable");
            return (Criteria) this;
        }

        public Criteria andAvatarIsNull() {
            addCriterion("`avatar` is null");
            return (Criteria) this;
        }

        public Criteria andAvatarIsNotNull() {
            addCriterion("`avatar` is not null");
            return (Criteria) this;
        }

        public Criteria andAvatarEqualTo(String value) {
            addCriterion("`avatar` =", value, "avatar");
            return (Criteria) this;
        }

        public Criteria andAvatarNotEqualTo(String value) {
            addCriterion("`avatar` <>", value, "avatar");
            return (Criteria) this;
        }

        public Criteria andAvatarGreaterThan(String value) {
            addCriterion("`avatar` >", value, "avatar");
            return (Criteria) this;
        }

        public Criteria andAvatarGreaterThanOrEqualTo(String value) {
            addCriterion("`avatar` >=", value, "avatar");
            return (Criteria) this;
        }

        public Criteria andAvatarLessThan(String value) {
            addCriterion("`avatar` <", value, "avatar");
            return (Criteria) this;
        }

        public Criteria andAvatarLessThanOrEqualTo(String value) {
            addCriterion("`avatar` <=", value, "avatar");
            return (Criteria) this;
        }

        public Criteria andAvatarLike(String value) {
            addCriterion("`avatar` like", value, "avatar");
            return (Criteria) this;
        }

        public Criteria andAvatarNotLike(String value) {
            addCriterion("`avatar` not like", value, "avatar");
            return (Criteria) this;
        }

        public Criteria andAvatarIn(List<String> values) {
            addCriterion("`avatar` in", values, "avatar");
            return (Criteria) this;
        }

        public Criteria andAvatarNotIn(List<String> values) {
            addCriterion("`avatar` not in", values, "avatar");
            return (Criteria) this;
        }

        public Criteria andAvatarBetween(String value1, String value2) {
            addCriterion("`avatar` between", value1, value2, "avatar");
            return (Criteria) this;
        }

        public Criteria andAvatarNotBetween(String value1, String value2) {
            addCriterion("`avatar` not between", value1, value2, "avatar");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("`status` is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("`status` is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(String value) {
            addCriterion("`status` =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(String value) {
            addCriterion("`status` <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(String value) {
            addCriterion("`status` >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(String value) {
            addCriterion("`status` >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(String value) {
            addCriterion("`status` <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(String value) {
            addCriterion("`status` <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLike(String value) {
            addCriterion("`status` like", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotLike(String value) {
            addCriterion("`status` not like", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<String> values) {
            addCriterion("`status` in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<String> values) {
            addCriterion("`status` not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(String value1, String value2) {
            addCriterion("`status` between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(String value1, String value2) {
            addCriterion("`status` not between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andModifiedIsNull() {
            addCriterion("`modified` is null");
            return (Criteria) this;
        }

        public Criteria andModifiedIsNotNull() {
            addCriterion("`modified` is not null");
            return (Criteria) this;
        }

        public Criteria andModifiedEqualTo(Date value) {
            addCriterion("`modified` =", value, "modified");
            return (Criteria) this;
        }

        public Criteria andModifiedNotEqualTo(Date value) {
            addCriterion("`modified` <>", value, "modified");
            return (Criteria) this;
        }

        public Criteria andModifiedGreaterThan(Date value) {
            addCriterion("`modified` >", value, "modified");
            return (Criteria) this;
        }

        public Criteria andModifiedGreaterThanOrEqualTo(Date value) {
            addCriterion("`modified` >=", value, "modified");
            return (Criteria) this;
        }

        public Criteria andModifiedLessThan(Date value) {
            addCriterion("`modified` <", value, "modified");
            return (Criteria) this;
        }

        public Criteria andModifiedLessThanOrEqualTo(Date value) {
            addCriterion("`modified` <=", value, "modified");
            return (Criteria) this;
        }

        public Criteria andModifiedIn(List<Date> values) {
            addCriterion("`modified` in", values, "modified");
            return (Criteria) this;
        }

        public Criteria andModifiedNotIn(List<Date> values) {
            addCriterion("`modified` not in", values, "modified");
            return (Criteria) this;
        }

        public Criteria andModifiedBetween(Date value1, Date value2) {
            addCriterion("`modified` between", value1, value2, "modified");
            return (Criteria) this;
        }

        public Criteria andModifiedNotBetween(Date value1, Date value2) {
            addCriterion("`modified` not between", value1, value2, "modified");
            return (Criteria) this;
        }

        public Criteria andOwnerIsNull() {
            addCriterion("`owner` is null");
            return (Criteria) this;
        }

        public Criteria andOwnerIsNotNull() {
            addCriterion("`owner` is not null");
            return (Criteria) this;
        }

        public Criteria andOwnerEqualTo(Integer value) {
            addCriterion("`owner` =", value, "owner");
            return (Criteria) this;
        }

        public Criteria andOwnerNotEqualTo(Integer value) {
            addCriterion("`owner` <>", value, "owner");
            return (Criteria) this;
        }

        public Criteria andOwnerGreaterThan(Integer value) {
            addCriterion("`owner` >", value, "owner");
            return (Criteria) this;
        }

        public Criteria andOwnerGreaterThanOrEqualTo(Integer value) {
            addCriterion("`owner` >=", value, "owner");
            return (Criteria) this;
        }

        public Criteria andOwnerLessThan(Integer value) {
            addCriterion("`owner` <", value, "owner");
            return (Criteria) this;
        }

        public Criteria andOwnerLessThanOrEqualTo(Integer value) {
            addCriterion("`owner` <=", value, "owner");
            return (Criteria) this;
        }

        public Criteria andOwnerIn(List<Integer> values) {
            addCriterion("`owner` in", values, "owner");
            return (Criteria) this;
        }

        public Criteria andOwnerNotIn(List<Integer> values) {
            addCriterion("`owner` not in", values, "owner");
            return (Criteria) this;
        }

        public Criteria andOwnerBetween(Integer value1, Integer value2) {
            addCriterion("`owner` between", value1, value2, "owner");
            return (Criteria) this;
        }

        public Criteria andOwnerNotBetween(Integer value1, Integer value2) {
            addCriterion("`owner` not between", value1, value2, "owner");
            return (Criteria) this;
        }

        public Criteria andModifierIsNull() {
            addCriterion("`modifier` is null");
            return (Criteria) this;
        }

        public Criteria andModifierIsNotNull() {
            addCriterion("`modifier` is not null");
            return (Criteria) this;
        }

        public Criteria andModifierEqualTo(Integer value) {
            addCriterion("`modifier` =", value, "modifier");
            return (Criteria) this;
        }

        public Criteria andModifierNotEqualTo(Integer value) {
            addCriterion("`modifier` <>", value, "modifier");
            return (Criteria) this;
        }

        public Criteria andModifierGreaterThan(Integer value) {
            addCriterion("`modifier` >", value, "modifier");
            return (Criteria) this;
        }

        public Criteria andModifierGreaterThanOrEqualTo(Integer value) {
            addCriterion("`modifier` >=", value, "modifier");
            return (Criteria) this;
        }

        public Criteria andModifierLessThan(Integer value) {
            addCriterion("`modifier` <", value, "modifier");
            return (Criteria) this;
        }

        public Criteria andModifierLessThanOrEqualTo(Integer value) {
            addCriterion("`modifier` <=", value, "modifier");
            return (Criteria) this;
        }

        public Criteria andModifierIn(List<Integer> values) {
            addCriterion("`modifier` in", values, "modifier");
            return (Criteria) this;
        }

        public Criteria andModifierNotIn(List<Integer> values) {
            addCriterion("`modifier` not in", values, "modifier");
            return (Criteria) this;
        }

        public Criteria andModifierBetween(Integer value1, Integer value2) {
            addCriterion("`modifier` between", value1, value2, "modifier");
            return (Criteria) this;
        }

        public Criteria andModifierNotBetween(Integer value1, Integer value2) {
            addCriterion("`modifier` not between", value1, value2, "modifier");
            return (Criteria) this;
        }

        public Criteria andAuthorIsNull() {
            addCriterion("`author` is null");
            return (Criteria) this;
        }

        public Criteria andAuthorIsNotNull() {
            addCriterion("`author` is not null");
            return (Criteria) this;
        }

        public Criteria andAuthorEqualTo(Integer value) {
            addCriterion("`author` =", value, "author");
            return (Criteria) this;
        }

        public Criteria andAuthorNotEqualTo(Integer value) {
            addCriterion("`author` <>", value, "author");
            return (Criteria) this;
        }

        public Criteria andAuthorGreaterThan(Integer value) {
            addCriterion("`author` >", value, "author");
            return (Criteria) this;
        }

        public Criteria andAuthorGreaterThanOrEqualTo(Integer value) {
            addCriterion("`author` >=", value, "author");
            return (Criteria) this;
        }

        public Criteria andAuthorLessThan(Integer value) {
            addCriterion("`author` <", value, "author");
            return (Criteria) this;
        }

        public Criteria andAuthorLessThanOrEqualTo(Integer value) {
            addCriterion("`author` <=", value, "author");
            return (Criteria) this;
        }

        public Criteria andAuthorIn(List<Integer> values) {
            addCriterion("`author` in", values, "author");
            return (Criteria) this;
        }

        public Criteria andAuthorNotIn(List<Integer> values) {
            addCriterion("`author` not in", values, "author");
            return (Criteria) this;
        }

        public Criteria andAuthorBetween(Integer value1, Integer value2) {
            addCriterion("`author` between", value1, value2, "author");
            return (Criteria) this;
        }

        public Criteria andAuthorNotBetween(Integer value1, Integer value2) {
            addCriterion("`author` not between", value1, value2, "author");
            return (Criteria) this;
        }

        public Criteria andWorkClassIsNull() {
            addCriterion("`work_class` is null");
            return (Criteria) this;
        }

        public Criteria andWorkClassIsNotNull() {
            addCriterion("`work_class` is not null");
            return (Criteria) this;
        }

        public Criteria andWorkClassEqualTo(String value) {
            addCriterion("`work_class` =", value, "workClass");
            return (Criteria) this;
        }

        public Criteria andWorkClassNotEqualTo(String value) {
            addCriterion("`work_class` <>", value, "workClass");
            return (Criteria) this;
        }

        public Criteria andWorkClassGreaterThan(String value) {
            addCriterion("`work_class` >", value, "workClass");
            return (Criteria) this;
        }

        public Criteria andWorkClassGreaterThanOrEqualTo(String value) {
            addCriterion("`work_class` >=", value, "workClass");
            return (Criteria) this;
        }

        public Criteria andWorkClassLessThan(String value) {
            addCriterion("`work_class` <", value, "workClass");
            return (Criteria) this;
        }

        public Criteria andWorkClassLessThanOrEqualTo(String value) {
            addCriterion("`work_class` <=", value, "workClass");
            return (Criteria) this;
        }

        public Criteria andWorkClassLike(String value) {
            addCriterion("`work_class` like", value, "workClass");
            return (Criteria) this;
        }

        public Criteria andWorkClassNotLike(String value) {
            addCriterion("`work_class` not like", value, "workClass");
            return (Criteria) this;
        }

        public Criteria andWorkClassIn(List<String> values) {
            addCriterion("`work_class` in", values, "workClass");
            return (Criteria) this;
        }

        public Criteria andWorkClassNotIn(List<String> values) {
            addCriterion("`work_class` not in", values, "workClass");
            return (Criteria) this;
        }

        public Criteria andWorkClassBetween(String value1, String value2) {
            addCriterion("`work_class` between", value1, value2, "workClass");
            return (Criteria) this;
        }

        public Criteria andWorkClassNotBetween(String value1, String value2) {
            addCriterion("`work_class` not between", value1, value2, "workClass");
            return (Criteria) this;
        }

        public Criteria andDataSourceModeIsNull() {
            addCriterion("`data_source_mode` is null");
            return (Criteria) this;
        }

        public Criteria andDataSourceModeIsNotNull() {
            addCriterion("`data_source_mode` is not null");
            return (Criteria) this;
        }

        public Criteria andDataSourceModeEqualTo(String value) {
            addCriterion("`data_source_mode` =", value, "dataSourceMode");
            return (Criteria) this;
        }

        public Criteria andDataSourceModeNotEqualTo(String value) {
            addCriterion("`data_source_mode` <>", value, "dataSourceMode");
            return (Criteria) this;
        }

        public Criteria andDataSourceModeGreaterThan(String value) {
            addCriterion("`data_source_mode` >", value, "dataSourceMode");
            return (Criteria) this;
        }

        public Criteria andDataSourceModeGreaterThanOrEqualTo(String value) {
            addCriterion("`data_source_mode` >=", value, "dataSourceMode");
            return (Criteria) this;
        }

        public Criteria andDataSourceModeLessThan(String value) {
            addCriterion("`data_source_mode` <", value, "dataSourceMode");
            return (Criteria) this;
        }

        public Criteria andDataSourceModeLessThanOrEqualTo(String value) {
            addCriterion("`data_source_mode` <=", value, "dataSourceMode");
            return (Criteria) this;
        }

        public Criteria andDataSourceModeLike(String value) {
            addCriterion("`data_source_mode` like", value, "dataSourceMode");
            return (Criteria) this;
        }

        public Criteria andDataSourceModeNotLike(String value) {
            addCriterion("`data_source_mode` not like", value, "dataSourceMode");
            return (Criteria) this;
        }

        public Criteria andDataSourceModeIn(List<String> values) {
            addCriterion("`data_source_mode` in", values, "dataSourceMode");
            return (Criteria) this;
        }

        public Criteria andDataSourceModeNotIn(List<String> values) {
            addCriterion("`data_source_mode` not in", values, "dataSourceMode");
            return (Criteria) this;
        }

        public Criteria andDataSourceModeBetween(String value1, String value2) {
            addCriterion("`data_source_mode` between", value1, value2, "dataSourceMode");
            return (Criteria) this;
        }

        public Criteria andDataSourceModeNotBetween(String value1, String value2) {
            addCriterion("`data_source_mode` not between", value1, value2, "dataSourceMode");
            return (Criteria) this;
        }

        public Criteria andReportModeIsNull() {
            addCriterion("`report_mode` is null");
            return (Criteria) this;
        }

        public Criteria andReportModeIsNotNull() {
            addCriterion("`report_mode` is not null");
            return (Criteria) this;
        }

        public Criteria andReportModeEqualTo(String value) {
            addCriterion("`report_mode` =", value, "reportMode");
            return (Criteria) this;
        }

        public Criteria andReportModeNotEqualTo(String value) {
            addCriterion("`report_mode` <>", value, "reportMode");
            return (Criteria) this;
        }

        public Criteria andReportModeGreaterThan(String value) {
            addCriterion("`report_mode` >", value, "reportMode");
            return (Criteria) this;
        }

        public Criteria andReportModeGreaterThanOrEqualTo(String value) {
            addCriterion("`report_mode` >=", value, "reportMode");
            return (Criteria) this;
        }

        public Criteria andReportModeLessThan(String value) {
            addCriterion("`report_mode` <", value, "reportMode");
            return (Criteria) this;
        }

        public Criteria andReportModeLessThanOrEqualTo(String value) {
            addCriterion("`report_mode` <=", value, "reportMode");
            return (Criteria) this;
        }

        public Criteria andReportModeLike(String value) {
            addCriterion("`report_mode` like", value, "reportMode");
            return (Criteria) this;
        }

        public Criteria andReportModeNotLike(String value) {
            addCriterion("`report_mode` not like", value, "reportMode");
            return (Criteria) this;
        }

        public Criteria andReportModeIn(List<String> values) {
            addCriterion("`report_mode` in", values, "reportMode");
            return (Criteria) this;
        }

        public Criteria andReportModeNotIn(List<String> values) {
            addCriterion("`report_mode` not in", values, "reportMode");
            return (Criteria) this;
        }

        public Criteria andReportModeBetween(String value1, String value2) {
            addCriterion("`report_mode` between", value1, value2, "reportMode");
            return (Criteria) this;
        }

        public Criteria andReportModeNotBetween(String value1, String value2) {
            addCriterion("`report_mode` not between", value1, value2, "reportMode");
            return (Criteria) this;
        }

        public Criteria andPidEqualTo(boolean condition, Integer value) {
            if (condition) {
                addCriterion("`pid` =", value, "pid");
            }
            return (Criteria) this;
        }

        public Criteria andPidGreaterThanOrEqualTo(boolean condition, Integer value) {
            if (condition) {
                addCriterion("`pid` >=", value, "pid");
            }
            return (Criteria) this;
        }

        public Criteria andPidIn(boolean condition, List<Integer> value) {
            if (condition) {
                addCriterion("`pid` in", value, "pid");
            }
            return (Criteria) this;
        }

        public Criteria andNameEqualTo(boolean condition, String value) {
            if (condition) {
                addCriterion("`name` =", value, "name");
            }
            return (Criteria) this;
        }

        public Criteria andNameGreaterThanOrEqualTo(boolean condition, String value) {
            if (condition) {
                addCriterion("`name` >=", value, "name");
            }
            return (Criteria) this;
        }

        public Criteria andNameIn(boolean condition, List<String> value) {
            if (condition) {
                addCriterion("`name` in", value, "name");
            }
            return (Criteria) this;
        }

        public Criteria andDescEqualTo(boolean condition, String value) {
            if (condition) {
                addCriterion("`desc` =", value, "desc");
            }
            return (Criteria) this;
        }

        public Criteria andDescGreaterThanOrEqualTo(boolean condition, String value) {
            if (condition) {
                addCriterion("`desc` >=", value, "desc");
            }
            return (Criteria) this;
        }

        public Criteria andDescIn(boolean condition, List<String> value) {
            if (condition) {
                addCriterion("`desc` in", value, "desc");
            }
            return (Criteria) this;
        }

        public Criteria andCreatedEqualTo(boolean condition, Date value) {
            if (condition) {
                addCriterion("`created` =", value, "created");
            }
            return (Criteria) this;
        }

        public Criteria andCreatedGreaterThanOrEqualTo(boolean condition, Date value) {
            if (condition) {
                addCriterion("`created` >=", value, "created");
            }
            return (Criteria) this;
        }

        public Criteria andCreatedIn(boolean condition, List<Date> value) {
            if (condition) {
                addCriterion("`created` in", value, "created");
            }
            return (Criteria) this;
        }

        public Criteria andEnableEqualTo(boolean condition, Boolean value) {
            if (condition) {
                addCriterion("`enable` =", value, "enable");
            }
            return (Criteria) this;
        }

        public Criteria andEnableGreaterThanOrEqualTo(boolean condition, Boolean value) {
            if (condition) {
                addCriterion("`enable` >=", value, "enable");
            }
            return (Criteria) this;
        }

        public Criteria andEnableIn(boolean condition, List<Boolean> value) {
            if (condition) {
                addCriterion("`enable` in", value, "enable");
            }
            return (Criteria) this;
        }

        public Criteria andAvatarEqualTo(boolean condition, String value) {
            if (condition) {
                addCriterion("`avatar` =", value, "avatar");
            }
            return (Criteria) this;
        }

        public Criteria andAvatarGreaterThanOrEqualTo(boolean condition, String value) {
            if (condition) {
                addCriterion("`avatar` >=", value, "avatar");
            }
            return (Criteria) this;
        }

        public Criteria andAvatarIn(boolean condition, List<String> value) {
            if (condition) {
                addCriterion("`avatar` in", value, "avatar");
            }
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(boolean condition, String value) {
            if (condition) {
                addCriterion("`status` =", value, "status");
            }
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(boolean condition, String value) {
            if (condition) {
                addCriterion("`status` >=", value, "status");
            }
            return (Criteria) this;
        }

        public Criteria andStatusIn(boolean condition, List<String> value) {
            if (condition) {
                addCriterion("`status` in", value, "status");
            }
            return (Criteria) this;
        }

        public Criteria andModifiedEqualTo(boolean condition, Date value) {
            if (condition) {
                addCriterion("`modified` =", value, "modified");
            }
            return (Criteria) this;
        }

        public Criteria andModifiedGreaterThanOrEqualTo(boolean condition, Date value) {
            if (condition) {
                addCriterion("`modified` >=", value, "modified");
            }
            return (Criteria) this;
        }

        public Criteria andModifiedIn(boolean condition, List<Date> value) {
            if (condition) {
                addCriterion("`modified` in", value, "modified");
            }
            return (Criteria) this;
        }

        public Criteria andOwnerEqualTo(boolean condition, Integer value) {
            if (condition) {
                addCriterion("`owner` =", value, "owner");
            }
            return (Criteria) this;
        }

        public Criteria andOwnerGreaterThanOrEqualTo(boolean condition, Integer value) {
            if (condition) {
                addCriterion("`owner` >=", value, "owner");
            }
            return (Criteria) this;
        }

        public Criteria andOwnerIn(boolean condition, List<Integer> value) {
            if (condition) {
                addCriterion("`owner` in", value, "owner");
            }
            return (Criteria) this;
        }

        public Criteria andModifierEqualTo(boolean condition, Integer value) {
            if (condition) {
                addCriterion("`modifier` =", value, "modifier");
            }
            return (Criteria) this;
        }

        public Criteria andModifierGreaterThanOrEqualTo(boolean condition, Integer value) {
            if (condition) {
                addCriterion("`modifier` >=", value, "modifier");
            }
            return (Criteria) this;
        }

        public Criteria andModifierIn(boolean condition, List<Integer> value) {
            if (condition) {
                addCriterion("`modifier` in", value, "modifier");
            }
            return (Criteria) this;
        }

        public Criteria andAuthorEqualTo(boolean condition, Integer value) {
            if (condition) {
                addCriterion("`author` =", value, "author");
            }
            return (Criteria) this;
        }

        public Criteria andAuthorGreaterThanOrEqualTo(boolean condition, Integer value) {
            if (condition) {
                addCriterion("`author` >=", value, "author");
            }
            return (Criteria) this;
        }

        public Criteria andAuthorIn(boolean condition, List<Integer> value) {
            if (condition) {
                addCriterion("`author` in", value, "author");
            }
            return (Criteria) this;
        }

        public Criteria andWorkClassEqualTo(boolean condition, String value) {
            if (condition) {
                addCriterion("`work_class` =", value, "workClass");
            }
            return (Criteria) this;
        }

        public Criteria andWorkClassGreaterThanOrEqualTo(boolean condition, String value) {
            if (condition) {
                addCriterion("`work_class` >=", value, "workClass");
            }
            return (Criteria) this;
        }

        public Criteria andWorkClassIn(boolean condition, List<String> value) {
            if (condition) {
                addCriterion("`work_class` in", value, "workClass");
            }
            return (Criteria) this;
        }

        public Criteria andDataSourceModeEqualTo(boolean condition, String value) {
            if (condition) {
                addCriterion("`data_source_mode` =", value, "dataSourceMode");
            }
            return (Criteria) this;
        }

        public Criteria andDataSourceModeGreaterThanOrEqualTo(boolean condition, String value) {
            if (condition) {
                addCriterion("`data_source_mode` >=", value, "dataSourceMode");
            }
            return (Criteria) this;
        }

        public Criteria andDataSourceModeIn(boolean condition, List<String> value) {
            if (condition) {
                addCriterion("`data_source_mode` in", value, "dataSourceMode");
            }
            return (Criteria) this;
        }

        public Criteria andReportModeEqualTo(boolean condition, String value) {
            if (condition) {
                addCriterion("`report_mode` =", value, "reportMode");
            }
            return (Criteria) this;
        }

        public Criteria andReportModeGreaterThanOrEqualTo(boolean condition, String value) {
            if (condition) {
                addCriterion("`report_mode` >=", value, "reportMode");
            }
            return (Criteria) this;
        }

        public Criteria andReportModeIn(boolean condition, List<String> value) {
            if (condition) {
                addCriterion("`report_mode` in", value, "reportMode");
            }
            return (Criteria) this;
        }
    }

    /**
     * null<p/>
     * BS_Plugin
     * @date 2021-08-22 14:53:49
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * Plugin
     * BS_Plugin
     * @date 2021-08-22 14:53:49
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}