/**
 * copyright (c) 2020 Kuta Service Framework
 * @author: mybatis generator
 */
package com.kuta.data.mysql.pojo;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class ScriptExample {
    /**
     * @date 2021-12-28 00:51:29
     */
    protected String orderByClause;

    /**
     * @date 2021-12-28 00:51:29
     */
    protected boolean distinct;

    /**
     * @date 2021-12-28 00:51:29
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BS_Script
     * @date 2021-12-28 00:51:29
     */
    public ScriptExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BS_Script
     * @date 2021-12-28 00:51:29
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BS_Script
     * @date 2021-12-28 00:51:29
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BS_Script
     * @date 2021-12-28 00:51:29
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BS_Script
     * @date 2021-12-28 00:51:29
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BS_Script
     * @date 2021-12-28 00:51:29
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BS_Script
     * @date 2021-12-28 00:51:29
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BS_Script
     * @date 2021-12-28 00:51:29
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BS_Script
     * @date 2021-12-28 00:51:29
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BS_Script
     * @date 2021-12-28 00:51:29
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BS_Script
     * @date 2021-12-28 00:51:29
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * Script
     * BS_Script
     * @date 2021-12-28 00:51:29
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andSidIsNull() {
            addCriterion("`sid` is null");
            return (Criteria) this;
        }

        public Criteria andSidIsNotNull() {
            addCriterion("`sid` is not null");
            return (Criteria) this;
        }

        public Criteria andSidEqualTo(Long value) {
            addCriterion("`sid` =", value, "sid");
            return (Criteria) this;
        }

        public Criteria andSidNotEqualTo(Long value) {
            addCriterion("`sid` <>", value, "sid");
            return (Criteria) this;
        }

        public Criteria andSidGreaterThan(Long value) {
            addCriterion("`sid` >", value, "sid");
            return (Criteria) this;
        }

        public Criteria andSidGreaterThanOrEqualTo(Long value) {
            addCriterion("`sid` >=", value, "sid");
            return (Criteria) this;
        }

        public Criteria andSidLessThan(Long value) {
            addCriterion("`sid` <", value, "sid");
            return (Criteria) this;
        }

        public Criteria andSidLessThanOrEqualTo(Long value) {
            addCriterion("`sid` <=", value, "sid");
            return (Criteria) this;
        }

        public Criteria andSidIn(List<Long> values) {
            addCriterion("`sid` in", values, "sid");
            return (Criteria) this;
        }

        public Criteria andSidNotIn(List<Long> values) {
            addCriterion("`sid` not in", values, "sid");
            return (Criteria) this;
        }

        public Criteria andSidBetween(Long value1, Long value2) {
            addCriterion("`sid` between", value1, value2, "sid");
            return (Criteria) this;
        }

        public Criteria andSidNotBetween(Long value1, Long value2) {
            addCriterion("`sid` not between", value1, value2, "sid");
            return (Criteria) this;
        }

        public Criteria andNameIsNull() {
            addCriterion("`name` is null");
            return (Criteria) this;
        }

        public Criteria andNameIsNotNull() {
            addCriterion("`name` is not null");
            return (Criteria) this;
        }

        public Criteria andNameEqualTo(String value) {
            addCriterion("`name` =", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotEqualTo(String value) {
            addCriterion("`name` <>", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThan(String value) {
            addCriterion("`name` >", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThanOrEqualTo(String value) {
            addCriterion("`name` >=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThan(String value) {
            addCriterion("`name` <", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThanOrEqualTo(String value) {
            addCriterion("`name` <=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLike(String value) {
            addCriterion("`name` like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotLike(String value) {
            addCriterion("`name` not like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameIn(List<String> values) {
            addCriterion("`name` in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotIn(List<String> values) {
            addCriterion("`name` not in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameBetween(String value1, String value2) {
            addCriterion("`name` between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotBetween(String value1, String value2) {
            addCriterion("`name` not between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andDescIsNull() {
            addCriterion("`desc` is null");
            return (Criteria) this;
        }

        public Criteria andDescIsNotNull() {
            addCriterion("`desc` is not null");
            return (Criteria) this;
        }

        public Criteria andDescEqualTo(String value) {
            addCriterion("`desc` =", value, "desc");
            return (Criteria) this;
        }

        public Criteria andDescNotEqualTo(String value) {
            addCriterion("`desc` <>", value, "desc");
            return (Criteria) this;
        }

        public Criteria andDescGreaterThan(String value) {
            addCriterion("`desc` >", value, "desc");
            return (Criteria) this;
        }

        public Criteria andDescGreaterThanOrEqualTo(String value) {
            addCriterion("`desc` >=", value, "desc");
            return (Criteria) this;
        }

        public Criteria andDescLessThan(String value) {
            addCriterion("`desc` <", value, "desc");
            return (Criteria) this;
        }

        public Criteria andDescLessThanOrEqualTo(String value) {
            addCriterion("`desc` <=", value, "desc");
            return (Criteria) this;
        }

        public Criteria andDescLike(String value) {
            addCriterion("`desc` like", value, "desc");
            return (Criteria) this;
        }

        public Criteria andDescNotLike(String value) {
            addCriterion("`desc` not like", value, "desc");
            return (Criteria) this;
        }

        public Criteria andDescIn(List<String> values) {
            addCriterion("`desc` in", values, "desc");
            return (Criteria) this;
        }

        public Criteria andDescNotIn(List<String> values) {
            addCriterion("`desc` not in", values, "desc");
            return (Criteria) this;
        }

        public Criteria andDescBetween(String value1, String value2) {
            addCriterion("`desc` between", value1, value2, "desc");
            return (Criteria) this;
        }

        public Criteria andDescNotBetween(String value1, String value2) {
            addCriterion("`desc` not between", value1, value2, "desc");
            return (Criteria) this;
        }

        public Criteria andCategoryIsNull() {
            addCriterion("`category` is null");
            return (Criteria) this;
        }

        public Criteria andCategoryIsNotNull() {
            addCriterion("`category` is not null");
            return (Criteria) this;
        }

        public Criteria andCategoryEqualTo(Integer value) {
            addCriterion("`category` =", value, "category");
            return (Criteria) this;
        }

        public Criteria andCategoryNotEqualTo(Integer value) {
            addCriterion("`category` <>", value, "category");
            return (Criteria) this;
        }

        public Criteria andCategoryGreaterThan(Integer value) {
            addCriterion("`category` >", value, "category");
            return (Criteria) this;
        }

        public Criteria andCategoryGreaterThanOrEqualTo(Integer value) {
            addCriterion("`category` >=", value, "category");
            return (Criteria) this;
        }

        public Criteria andCategoryLessThan(Integer value) {
            addCriterion("`category` <", value, "category");
            return (Criteria) this;
        }

        public Criteria andCategoryLessThanOrEqualTo(Integer value) {
            addCriterion("`category` <=", value, "category");
            return (Criteria) this;
        }

        public Criteria andCategoryIn(List<Integer> values) {
            addCriterion("`category` in", values, "category");
            return (Criteria) this;
        }

        public Criteria andCategoryNotIn(List<Integer> values) {
            addCriterion("`category` not in", values, "category");
            return (Criteria) this;
        }

        public Criteria andCategoryBetween(Integer value1, Integer value2) {
            addCriterion("`category` between", value1, value2, "category");
            return (Criteria) this;
        }

        public Criteria andCategoryNotBetween(Integer value1, Integer value2) {
            addCriterion("`category` not between", value1, value2, "category");
            return (Criteria) this;
        }

        public Criteria andCategoryArrayIsNull() {
            addCriterion("`category_array` is null");
            return (Criteria) this;
        }

        public Criteria andCategoryArrayIsNotNull() {
            addCriterion("`category_array` is not null");
            return (Criteria) this;
        }

        public Criteria andCategoryArrayEqualTo(String value) {
            addCriterion("`category_array` =", value, "categoryArray");
            return (Criteria) this;
        }

        public Criteria andCategoryArrayNotEqualTo(String value) {
            addCriterion("`category_array` <>", value, "categoryArray");
            return (Criteria) this;
        }

        public Criteria andCategoryArrayGreaterThan(String value) {
            addCriterion("`category_array` >", value, "categoryArray");
            return (Criteria) this;
        }

        public Criteria andCategoryArrayGreaterThanOrEqualTo(String value) {
            addCriterion("`category_array` >=", value, "categoryArray");
            return (Criteria) this;
        }

        public Criteria andCategoryArrayLessThan(String value) {
            addCriterion("`category_array` <", value, "categoryArray");
            return (Criteria) this;
        }

        public Criteria andCategoryArrayLessThanOrEqualTo(String value) {
            addCriterion("`category_array` <=", value, "categoryArray");
            return (Criteria) this;
        }

        public Criteria andCategoryArrayLike(String value) {
            addCriterion("`category_array` like", value, "categoryArray");
            return (Criteria) this;
        }

        public Criteria andCategoryArrayNotLike(String value) {
            addCriterion("`category_array` not like", value, "categoryArray");
            return (Criteria) this;
        }

        public Criteria andCategoryArrayIn(List<String> values) {
            addCriterion("`category_array` in", values, "categoryArray");
            return (Criteria) this;
        }

        public Criteria andCategoryArrayNotIn(List<String> values) {
            addCriterion("`category_array` not in", values, "categoryArray");
            return (Criteria) this;
        }

        public Criteria andCategoryArrayBetween(String value1, String value2) {
            addCriterion("`category_array` between", value1, value2, "categoryArray");
            return (Criteria) this;
        }

        public Criteria andCategoryArrayNotBetween(String value1, String value2) {
            addCriterion("`category_array` not between", value1, value2, "categoryArray");
            return (Criteria) this;
        }

        public Criteria andCategoryNamesIsNull() {
            addCriterion("`category_names` is null");
            return (Criteria) this;
        }

        public Criteria andCategoryNamesIsNotNull() {
            addCriterion("`category_names` is not null");
            return (Criteria) this;
        }

        public Criteria andCategoryNamesEqualTo(String value) {
            addCriterion("`category_names` =", value, "categoryNames");
            return (Criteria) this;
        }

        public Criteria andCategoryNamesNotEqualTo(String value) {
            addCriterion("`category_names` <>", value, "categoryNames");
            return (Criteria) this;
        }

        public Criteria andCategoryNamesGreaterThan(String value) {
            addCriterion("`category_names` >", value, "categoryNames");
            return (Criteria) this;
        }

        public Criteria andCategoryNamesGreaterThanOrEqualTo(String value) {
            addCriterion("`category_names` >=", value, "categoryNames");
            return (Criteria) this;
        }

        public Criteria andCategoryNamesLessThan(String value) {
            addCriterion("`category_names` <", value, "categoryNames");
            return (Criteria) this;
        }

        public Criteria andCategoryNamesLessThanOrEqualTo(String value) {
            addCriterion("`category_names` <=", value, "categoryNames");
            return (Criteria) this;
        }

        public Criteria andCategoryNamesLike(String value) {
            addCriterion("`category_names` like", value, "categoryNames");
            return (Criteria) this;
        }

        public Criteria andCategoryNamesNotLike(String value) {
            addCriterion("`category_names` not like", value, "categoryNames");
            return (Criteria) this;
        }

        public Criteria andCategoryNamesIn(List<String> values) {
            addCriterion("`category_names` in", values, "categoryNames");
            return (Criteria) this;
        }

        public Criteria andCategoryNamesNotIn(List<String> values) {
            addCriterion("`category_names` not in", values, "categoryNames");
            return (Criteria) this;
        }

        public Criteria andCategoryNamesBetween(String value1, String value2) {
            addCriterion("`category_names` between", value1, value2, "categoryNames");
            return (Criteria) this;
        }

        public Criteria andCategoryNamesNotBetween(String value1, String value2) {
            addCriterion("`category_names` not between", value1, value2, "categoryNames");
            return (Criteria) this;
        }

        public Criteria andFileNameIsNull() {
            addCriterion("`file_name` is null");
            return (Criteria) this;
        }

        public Criteria andFileNameIsNotNull() {
            addCriterion("`file_name` is not null");
            return (Criteria) this;
        }

        public Criteria andFileNameEqualTo(String value) {
            addCriterion("`file_name` =", value, "fileName");
            return (Criteria) this;
        }

        public Criteria andFileNameNotEqualTo(String value) {
            addCriterion("`file_name` <>", value, "fileName");
            return (Criteria) this;
        }

        public Criteria andFileNameGreaterThan(String value) {
            addCriterion("`file_name` >", value, "fileName");
            return (Criteria) this;
        }

        public Criteria andFileNameGreaterThanOrEqualTo(String value) {
            addCriterion("`file_name` >=", value, "fileName");
            return (Criteria) this;
        }

        public Criteria andFileNameLessThan(String value) {
            addCriterion("`file_name` <", value, "fileName");
            return (Criteria) this;
        }

        public Criteria andFileNameLessThanOrEqualTo(String value) {
            addCriterion("`file_name` <=", value, "fileName");
            return (Criteria) this;
        }

        public Criteria andFileNameLike(String value) {
            addCriterion("`file_name` like", value, "fileName");
            return (Criteria) this;
        }

        public Criteria andFileNameNotLike(String value) {
            addCriterion("`file_name` not like", value, "fileName");
            return (Criteria) this;
        }

        public Criteria andFileNameIn(List<String> values) {
            addCriterion("`file_name` in", values, "fileName");
            return (Criteria) this;
        }

        public Criteria andFileNameNotIn(List<String> values) {
            addCriterion("`file_name` not in", values, "fileName");
            return (Criteria) this;
        }

        public Criteria andFileNameBetween(String value1, String value2) {
            addCriterion("`file_name` between", value1, value2, "fileName");
            return (Criteria) this;
        }

        public Criteria andFileNameNotBetween(String value1, String value2) {
            addCriterion("`file_name` not between", value1, value2, "fileName");
            return (Criteria) this;
        }

        public Criteria andResUrlIsNull() {
            addCriterion("`res_url` is null");
            return (Criteria) this;
        }

        public Criteria andResUrlIsNotNull() {
            addCriterion("`res_url` is not null");
            return (Criteria) this;
        }

        public Criteria andResUrlEqualTo(String value) {
            addCriterion("`res_url` =", value, "resUrl");
            return (Criteria) this;
        }

        public Criteria andResUrlNotEqualTo(String value) {
            addCriterion("`res_url` <>", value, "resUrl");
            return (Criteria) this;
        }

        public Criteria andResUrlGreaterThan(String value) {
            addCriterion("`res_url` >", value, "resUrl");
            return (Criteria) this;
        }

        public Criteria andResUrlGreaterThanOrEqualTo(String value) {
            addCriterion("`res_url` >=", value, "resUrl");
            return (Criteria) this;
        }

        public Criteria andResUrlLessThan(String value) {
            addCriterion("`res_url` <", value, "resUrl");
            return (Criteria) this;
        }

        public Criteria andResUrlLessThanOrEqualTo(String value) {
            addCriterion("`res_url` <=", value, "resUrl");
            return (Criteria) this;
        }

        public Criteria andResUrlLike(String value) {
            addCriterion("`res_url` like", value, "resUrl");
            return (Criteria) this;
        }

        public Criteria andResUrlNotLike(String value) {
            addCriterion("`res_url` not like", value, "resUrl");
            return (Criteria) this;
        }

        public Criteria andResUrlIn(List<String> values) {
            addCriterion("`res_url` in", values, "resUrl");
            return (Criteria) this;
        }

        public Criteria andResUrlNotIn(List<String> values) {
            addCriterion("`res_url` not in", values, "resUrl");
            return (Criteria) this;
        }

        public Criteria andResUrlBetween(String value1, String value2) {
            addCriterion("`res_url` between", value1, value2, "resUrl");
            return (Criteria) this;
        }

        public Criteria andResUrlNotBetween(String value1, String value2) {
            addCriterion("`res_url` not between", value1, value2, "resUrl");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("`status` is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("`status` is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(String value) {
            addCriterion("`status` =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(String value) {
            addCriterion("`status` <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(String value) {
            addCriterion("`status` >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(String value) {
            addCriterion("`status` >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(String value) {
            addCriterion("`status` <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(String value) {
            addCriterion("`status` <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLike(String value) {
            addCriterion("`status` like", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotLike(String value) {
            addCriterion("`status` not like", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<String> values) {
            addCriterion("`status` in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<String> values) {
            addCriterion("`status` not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(String value1, String value2) {
            addCriterion("`status` between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(String value1, String value2) {
            addCriterion("`status` not between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andUidIsNull() {
            addCriterion("`uid` is null");
            return (Criteria) this;
        }

        public Criteria andUidIsNotNull() {
            addCriterion("`uid` is not null");
            return (Criteria) this;
        }

        public Criteria andUidEqualTo(Integer value) {
            addCriterion("`uid` =", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidNotEqualTo(Integer value) {
            addCriterion("`uid` <>", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidGreaterThan(Integer value) {
            addCriterion("`uid` >", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidGreaterThanOrEqualTo(Integer value) {
            addCriterion("`uid` >=", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidLessThan(Integer value) {
            addCriterion("`uid` <", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidLessThanOrEqualTo(Integer value) {
            addCriterion("`uid` <=", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidIn(List<Integer> values) {
            addCriterion("`uid` in", values, "uid");
            return (Criteria) this;
        }

        public Criteria andUidNotIn(List<Integer> values) {
            addCriterion("`uid` not in", values, "uid");
            return (Criteria) this;
        }

        public Criteria andUidBetween(Integer value1, Integer value2) {
            addCriterion("`uid` between", value1, value2, "uid");
            return (Criteria) this;
        }

        public Criteria andUidNotBetween(Integer value1, Integer value2) {
            addCriterion("`uid` not between", value1, value2, "uid");
            return (Criteria) this;
        }

        public Criteria andOidIsNull() {
            addCriterion("`oid` is null");
            return (Criteria) this;
        }

        public Criteria andOidIsNotNull() {
            addCriterion("`oid` is not null");
            return (Criteria) this;
        }

        public Criteria andOidEqualTo(Integer value) {
            addCriterion("`oid` =", value, "oid");
            return (Criteria) this;
        }

        public Criteria andOidNotEqualTo(Integer value) {
            addCriterion("`oid` <>", value, "oid");
            return (Criteria) this;
        }

        public Criteria andOidGreaterThan(Integer value) {
            addCriterion("`oid` >", value, "oid");
            return (Criteria) this;
        }

        public Criteria andOidGreaterThanOrEqualTo(Integer value) {
            addCriterion("`oid` >=", value, "oid");
            return (Criteria) this;
        }

        public Criteria andOidLessThan(Integer value) {
            addCriterion("`oid` <", value, "oid");
            return (Criteria) this;
        }

        public Criteria andOidLessThanOrEqualTo(Integer value) {
            addCriterion("`oid` <=", value, "oid");
            return (Criteria) this;
        }

        public Criteria andOidIn(List<Integer> values) {
            addCriterion("`oid` in", values, "oid");
            return (Criteria) this;
        }

        public Criteria andOidNotIn(List<Integer> values) {
            addCriterion("`oid` not in", values, "oid");
            return (Criteria) this;
        }

        public Criteria andOidBetween(Integer value1, Integer value2) {
            addCriterion("`oid` between", value1, value2, "oid");
            return (Criteria) this;
        }

        public Criteria andOidNotBetween(Integer value1, Integer value2) {
            addCriterion("`oid` not between", value1, value2, "oid");
            return (Criteria) this;
        }

        public Criteria andCreatedIsNull() {
            addCriterion("`created` is null");
            return (Criteria) this;
        }

        public Criteria andCreatedIsNotNull() {
            addCriterion("`created` is not null");
            return (Criteria) this;
        }

        public Criteria andCreatedEqualTo(Date value) {
            addCriterion("`created` =", value, "created");
            return (Criteria) this;
        }

        public Criteria andCreatedNotEqualTo(Date value) {
            addCriterion("`created` <>", value, "created");
            return (Criteria) this;
        }

        public Criteria andCreatedGreaterThan(Date value) {
            addCriterion("`created` >", value, "created");
            return (Criteria) this;
        }

        public Criteria andCreatedGreaterThanOrEqualTo(Date value) {
            addCriterion("`created` >=", value, "created");
            return (Criteria) this;
        }

        public Criteria andCreatedLessThan(Date value) {
            addCriterion("`created` <", value, "created");
            return (Criteria) this;
        }

        public Criteria andCreatedLessThanOrEqualTo(Date value) {
            addCriterion("`created` <=", value, "created");
            return (Criteria) this;
        }

        public Criteria andCreatedIn(List<Date> values) {
            addCriterion("`created` in", values, "created");
            return (Criteria) this;
        }

        public Criteria andCreatedNotIn(List<Date> values) {
            addCriterion("`created` not in", values, "created");
            return (Criteria) this;
        }

        public Criteria andCreatedBetween(Date value1, Date value2) {
            addCriterion("`created` between", value1, value2, "created");
            return (Criteria) this;
        }

        public Criteria andCreatedNotBetween(Date value1, Date value2) {
            addCriterion("`created` not between", value1, value2, "created");
            return (Criteria) this;
        }

        public Criteria andModifiedIsNull() {
            addCriterion("`modified` is null");
            return (Criteria) this;
        }

        public Criteria andModifiedIsNotNull() {
            addCriterion("`modified` is not null");
            return (Criteria) this;
        }

        public Criteria andModifiedEqualTo(Date value) {
            addCriterion("`modified` =", value, "modified");
            return (Criteria) this;
        }

        public Criteria andModifiedNotEqualTo(Date value) {
            addCriterion("`modified` <>", value, "modified");
            return (Criteria) this;
        }

        public Criteria andModifiedGreaterThan(Date value) {
            addCriterion("`modified` >", value, "modified");
            return (Criteria) this;
        }

        public Criteria andModifiedGreaterThanOrEqualTo(Date value) {
            addCriterion("`modified` >=", value, "modified");
            return (Criteria) this;
        }

        public Criteria andModifiedLessThan(Date value) {
            addCriterion("`modified` <", value, "modified");
            return (Criteria) this;
        }

        public Criteria andModifiedLessThanOrEqualTo(Date value) {
            addCriterion("`modified` <=", value, "modified");
            return (Criteria) this;
        }

        public Criteria andModifiedIn(List<Date> values) {
            addCriterion("`modified` in", values, "modified");
            return (Criteria) this;
        }

        public Criteria andModifiedNotIn(List<Date> values) {
            addCriterion("`modified` not in", values, "modified");
            return (Criteria) this;
        }

        public Criteria andModifiedBetween(Date value1, Date value2) {
            addCriterion("`modified` between", value1, value2, "modified");
            return (Criteria) this;
        }

        public Criteria andModifiedNotBetween(Date value1, Date value2) {
            addCriterion("`modified` not between", value1, value2, "modified");
            return (Criteria) this;
        }

        public Criteria andBackupSidIsNull() {
            addCriterion("`backup_sid` is null");
            return (Criteria) this;
        }

        public Criteria andBackupSidIsNotNull() {
            addCriterion("`backup_sid` is not null");
            return (Criteria) this;
        }

        public Criteria andBackupSidEqualTo(String value) {
            addCriterion("`backup_sid` =", value, "backupSid");
            return (Criteria) this;
        }

        public Criteria andBackupSidNotEqualTo(String value) {
            addCriterion("`backup_sid` <>", value, "backupSid");
            return (Criteria) this;
        }

        public Criteria andBackupSidGreaterThan(String value) {
            addCriterion("`backup_sid` >", value, "backupSid");
            return (Criteria) this;
        }

        public Criteria andBackupSidGreaterThanOrEqualTo(String value) {
            addCriterion("`backup_sid` >=", value, "backupSid");
            return (Criteria) this;
        }

        public Criteria andBackupSidLessThan(String value) {
            addCriterion("`backup_sid` <", value, "backupSid");
            return (Criteria) this;
        }

        public Criteria andBackupSidLessThanOrEqualTo(String value) {
            addCriterion("`backup_sid` <=", value, "backupSid");
            return (Criteria) this;
        }

        public Criteria andBackupSidLike(String value) {
            addCriterion("`backup_sid` like", value, "backupSid");
            return (Criteria) this;
        }

        public Criteria andBackupSidNotLike(String value) {
            addCriterion("`backup_sid` not like", value, "backupSid");
            return (Criteria) this;
        }

        public Criteria andBackupSidIn(List<String> values) {
            addCriterion("`backup_sid` in", values, "backupSid");
            return (Criteria) this;
        }

        public Criteria andBackupSidNotIn(List<String> values) {
            addCriterion("`backup_sid` not in", values, "backupSid");
            return (Criteria) this;
        }

        public Criteria andBackupSidBetween(String value1, String value2) {
            addCriterion("`backup_sid` between", value1, value2, "backupSid");
            return (Criteria) this;
        }

        public Criteria andBackupSidNotBetween(String value1, String value2) {
            addCriterion("`backup_sid` not between", value1, value2, "backupSid");
            return (Criteria) this;
        }

        public Criteria andSidEqualTo(boolean condition, Long value) {
            if (condition) {
                addCriterion("`sid` =", value, "sid");
            }
            return (Criteria) this;
        }

        public Criteria andSidGreaterThanOrEqualTo(boolean condition, Long value) {
            if (condition) {
                addCriterion("`sid` >=", value, "sid");
            }
            return (Criteria) this;
        }

        public Criteria andSidIn(boolean condition, List<Long> value) {
            if (condition) {
                addCriterion("`sid` in", value, "sid");
            }
            return (Criteria) this;
        }

        public Criteria andNameEqualTo(boolean condition, String value) {
            if (condition) {
                addCriterion("`name` =", value, "name");
            }
            return (Criteria) this;
        }

        public Criteria andNameGreaterThanOrEqualTo(boolean condition, String value) {
            if (condition) {
                addCriterion("`name` >=", value, "name");
            }
            return (Criteria) this;
        }

        public Criteria andNameIn(boolean condition, List<String> value) {
            if (condition) {
                addCriterion("`name` in", value, "name");
            }
            return (Criteria) this;
        }

        public Criteria andDescEqualTo(boolean condition, String value) {
            if (condition) {
                addCriterion("`desc` =", value, "desc");
            }
            return (Criteria) this;
        }

        public Criteria andDescGreaterThanOrEqualTo(boolean condition, String value) {
            if (condition) {
                addCriterion("`desc` >=", value, "desc");
            }
            return (Criteria) this;
        }

        public Criteria andDescIn(boolean condition, List<String> value) {
            if (condition) {
                addCriterion("`desc` in", value, "desc");
            }
            return (Criteria) this;
        }

        public Criteria andCategoryEqualTo(boolean condition, Integer value) {
            if (condition) {
                addCriterion("`category` =", value, "category");
            }
            return (Criteria) this;
        }

        public Criteria andCategoryGreaterThanOrEqualTo(boolean condition, Integer value) {
            if (condition) {
                addCriterion("`category` >=", value, "category");
            }
            return (Criteria) this;
        }

        public Criteria andCategoryIn(boolean condition, List<Integer> value) {
            if (condition) {
                addCriterion("`category` in", value, "category");
            }
            return (Criteria) this;
        }

        public Criteria andCategoryArrayEqualTo(boolean condition, String value) {
            if (condition) {
                addCriterion("`category_array` =", value, "categoryArray");
            }
            return (Criteria) this;
        }

        public Criteria andCategoryArrayGreaterThanOrEqualTo(boolean condition, String value) {
            if (condition) {
                addCriterion("`category_array` >=", value, "categoryArray");
            }
            return (Criteria) this;
        }

        public Criteria andCategoryArrayIn(boolean condition, List<String> value) {
            if (condition) {
                addCriterion("`category_array` in", value, "categoryArray");
            }
            return (Criteria) this;
        }

        public Criteria andCategoryNamesEqualTo(boolean condition, String value) {
            if (condition) {
                addCriterion("`category_names` =", value, "categoryNames");
            }
            return (Criteria) this;
        }

        public Criteria andCategoryNamesGreaterThanOrEqualTo(boolean condition, String value) {
            if (condition) {
                addCriterion("`category_names` >=", value, "categoryNames");
            }
            return (Criteria) this;
        }

        public Criteria andCategoryNamesIn(boolean condition, List<String> value) {
            if (condition) {
                addCriterion("`category_names` in", value, "categoryNames");
            }
            return (Criteria) this;
        }

        public Criteria andFileNameEqualTo(boolean condition, String value) {
            if (condition) {
                addCriterion("`file_name` =", value, "fileName");
            }
            return (Criteria) this;
        }

        public Criteria andFileNameGreaterThanOrEqualTo(boolean condition, String value) {
            if (condition) {
                addCriterion("`file_name` >=", value, "fileName");
            }
            return (Criteria) this;
        }

        public Criteria andFileNameIn(boolean condition, List<String> value) {
            if (condition) {
                addCriterion("`file_name` in", value, "fileName");
            }
            return (Criteria) this;
        }

        public Criteria andResUrlEqualTo(boolean condition, String value) {
            if (condition) {
                addCriterion("`res_url` =", value, "resUrl");
            }
            return (Criteria) this;
        }

        public Criteria andResUrlGreaterThanOrEqualTo(boolean condition, String value) {
            if (condition) {
                addCriterion("`res_url` >=", value, "resUrl");
            }
            return (Criteria) this;
        }

        public Criteria andResUrlIn(boolean condition, List<String> value) {
            if (condition) {
                addCriterion("`res_url` in", value, "resUrl");
            }
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(boolean condition, String value) {
            if (condition) {
                addCriterion("`status` =", value, "status");
            }
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(boolean condition, String value) {
            if (condition) {
                addCriterion("`status` >=", value, "status");
            }
            return (Criteria) this;
        }

        public Criteria andStatusIn(boolean condition, List<String> value) {
            if (condition) {
                addCriterion("`status` in", value, "status");
            }
            return (Criteria) this;
        }

        public Criteria andUidEqualTo(boolean condition, Integer value) {
            if (condition) {
                addCriterion("`uid` =", value, "uid");
            }
            return (Criteria) this;
        }

        public Criteria andUidGreaterThanOrEqualTo(boolean condition, Integer value) {
            if (condition) {
                addCriterion("`uid` >=", value, "uid");
            }
            return (Criteria) this;
        }

        public Criteria andUidIn(boolean condition, List<Integer> value) {
            if (condition) {
                addCriterion("`uid` in", value, "uid");
            }
            return (Criteria) this;
        }

        public Criteria andOidEqualTo(boolean condition, Integer value) {
            if (condition) {
                addCriterion("`oid` =", value, "oid");
            }
            return (Criteria) this;
        }

        public Criteria andOidGreaterThanOrEqualTo(boolean condition, Integer value) {
            if (condition) {
                addCriterion("`oid` >=", value, "oid");
            }
            return (Criteria) this;
        }

        public Criteria andOidIn(boolean condition, List<Integer> value) {
            if (condition) {
                addCriterion("`oid` in", value, "oid");
            }
            return (Criteria) this;
        }

        public Criteria andCreatedEqualTo(boolean condition, Date value) {
            if (condition) {
                addCriterion("`created` =", value, "created");
            }
            return (Criteria) this;
        }

        public Criteria andCreatedGreaterThanOrEqualTo(boolean condition, Date value) {
            if (condition) {
                addCriterion("`created` >=", value, "created");
            }
            return (Criteria) this;
        }

        public Criteria andCreatedIn(boolean condition, List<Date> value) {
            if (condition) {
                addCriterion("`created` in", value, "created");
            }
            return (Criteria) this;
        }

        public Criteria andModifiedEqualTo(boolean condition, Date value) {
            if (condition) {
                addCriterion("`modified` =", value, "modified");
            }
            return (Criteria) this;
        }

        public Criteria andModifiedGreaterThanOrEqualTo(boolean condition, Date value) {
            if (condition) {
                addCriterion("`modified` >=", value, "modified");
            }
            return (Criteria) this;
        }

        public Criteria andModifiedIn(boolean condition, List<Date> value) {
            if (condition) {
                addCriterion("`modified` in", value, "modified");
            }
            return (Criteria) this;
        }

        public Criteria andBackupSidEqualTo(boolean condition, String value) {
            if (condition) {
                addCriterion("`backup_sid` =", value, "backupSid");
            }
            return (Criteria) this;
        }

        public Criteria andBackupSidGreaterThanOrEqualTo(boolean condition, String value) {
            if (condition) {
                addCriterion("`backup_sid` >=", value, "backupSid");
            }
            return (Criteria) this;
        }

        public Criteria andBackupSidIn(boolean condition, List<String> value) {
            if (condition) {
                addCriterion("`backup_sid` in", value, "backupSid");
            }
            return (Criteria) this;
        }
    }

    /**
     * null<p/>
     * BS_Script
     * @date 2021-12-28 00:51:29
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * Script
     * BS_Script
     * @date 2021-12-28 00:51:29
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}