/**
 * copyright (c) 2020 Kuta Service Framework
 * @author: mybatis generator
 */
package com.kuta.data.mysql.pojo;

import java.util.ArrayList;
import java.util.List;

public class SystemConfigExample {
    /**
     * @date 2021-07-15 12:55:28
     */
    protected String orderByClause;

    /**
     * @date 2021-07-15 12:55:28
     */
    protected boolean distinct;

    /**
     * @date 2021-07-15 12:55:28
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BS_Config
     * @date 2021-07-15 12:55:28
     */
    public SystemConfigExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BS_Config
     * @date 2021-07-15 12:55:28
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BS_Config
     * @date 2021-07-15 12:55:28
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BS_Config
     * @date 2021-07-15 12:55:28
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BS_Config
     * @date 2021-07-15 12:55:28
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BS_Config
     * @date 2021-07-15 12:55:28
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BS_Config
     * @date 2021-07-15 12:55:28
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BS_Config
     * @date 2021-07-15 12:55:28
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BS_Config
     * @date 2021-07-15 12:55:28
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BS_Config
     * @date 2021-07-15 12:55:28
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BS_Config
     * @date 2021-07-15 12:55:28
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * SystemConfig
     * BS_Config
     * @date 2021-07-15 12:55:28
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andKeyIsNull() {
            addCriterion("`key` is null");
            return (Criteria) this;
        }

        public Criteria andKeyIsNotNull() {
            addCriterion("`key` is not null");
            return (Criteria) this;
        }

        public Criteria andKeyEqualTo(String value) {
            addCriterion("`key` =", value, "key");
            return (Criteria) this;
        }

        public Criteria andKeyNotEqualTo(String value) {
            addCriterion("`key` <>", value, "key");
            return (Criteria) this;
        }

        public Criteria andKeyGreaterThan(String value) {
            addCriterion("`key` >", value, "key");
            return (Criteria) this;
        }

        public Criteria andKeyGreaterThanOrEqualTo(String value) {
            addCriterion("`key` >=", value, "key");
            return (Criteria) this;
        }

        public Criteria andKeyLessThan(String value) {
            addCriterion("`key` <", value, "key");
            return (Criteria) this;
        }

        public Criteria andKeyLessThanOrEqualTo(String value) {
            addCriterion("`key` <=", value, "key");
            return (Criteria) this;
        }

        public Criteria andKeyLike(String value) {
            addCriterion("`key` like", value, "key");
            return (Criteria) this;
        }

        public Criteria andKeyNotLike(String value) {
            addCriterion("`key` not like", value, "key");
            return (Criteria) this;
        }

        public Criteria andKeyIn(List<String> values) {
            addCriterion("`key` in", values, "key");
            return (Criteria) this;
        }

        public Criteria andKeyNotIn(List<String> values) {
            addCriterion("`key` not in", values, "key");
            return (Criteria) this;
        }

        public Criteria andKeyBetween(String value1, String value2) {
            addCriterion("`key` between", value1, value2, "key");
            return (Criteria) this;
        }

        public Criteria andKeyNotBetween(String value1, String value2) {
            addCriterion("`key` not between", value1, value2, "key");
            return (Criteria) this;
        }

        public Criteria andValueIsNull() {
            addCriterion("`value` is null");
            return (Criteria) this;
        }

        public Criteria andValueIsNotNull() {
            addCriterion("`value` is not null");
            return (Criteria) this;
        }

        public Criteria andValueEqualTo(String value) {
            addCriterion("`value` =", value, "value");
            return (Criteria) this;
        }

        public Criteria andValueNotEqualTo(String value) {
            addCriterion("`value` <>", value, "value");
            return (Criteria) this;
        }

        public Criteria andValueGreaterThan(String value) {
            addCriterion("`value` >", value, "value");
            return (Criteria) this;
        }

        public Criteria andValueGreaterThanOrEqualTo(String value) {
            addCriterion("`value` >=", value, "value");
            return (Criteria) this;
        }

        public Criteria andValueLessThan(String value) {
            addCriterion("`value` <", value, "value");
            return (Criteria) this;
        }

        public Criteria andValueLessThanOrEqualTo(String value) {
            addCriterion("`value` <=", value, "value");
            return (Criteria) this;
        }

        public Criteria andValueLike(String value) {
            addCriterion("`value` like", value, "value");
            return (Criteria) this;
        }

        public Criteria andValueNotLike(String value) {
            addCriterion("`value` not like", value, "value");
            return (Criteria) this;
        }

        public Criteria andValueIn(List<String> values) {
            addCriterion("`value` in", values, "value");
            return (Criteria) this;
        }

        public Criteria andValueNotIn(List<String> values) {
            addCriterion("`value` not in", values, "value");
            return (Criteria) this;
        }

        public Criteria andValueBetween(String value1, String value2) {
            addCriterion("`value` between", value1, value2, "value");
            return (Criteria) this;
        }

        public Criteria andValueNotBetween(String value1, String value2) {
            addCriterion("`value` not between", value1, value2, "value");
            return (Criteria) this;
        }

        public Criteria andDefaultValIsNull() {
            addCriterion("`default_val` is null");
            return (Criteria) this;
        }

        public Criteria andDefaultValIsNotNull() {
            addCriterion("`default_val` is not null");
            return (Criteria) this;
        }

        public Criteria andDefaultValEqualTo(String value) {
            addCriterion("`default_val` =", value, "defaultVal");
            return (Criteria) this;
        }

        public Criteria andDefaultValNotEqualTo(String value) {
            addCriterion("`default_val` <>", value, "defaultVal");
            return (Criteria) this;
        }

        public Criteria andDefaultValGreaterThan(String value) {
            addCriterion("`default_val` >", value, "defaultVal");
            return (Criteria) this;
        }

        public Criteria andDefaultValGreaterThanOrEqualTo(String value) {
            addCriterion("`default_val` >=", value, "defaultVal");
            return (Criteria) this;
        }

        public Criteria andDefaultValLessThan(String value) {
            addCriterion("`default_val` <", value, "defaultVal");
            return (Criteria) this;
        }

        public Criteria andDefaultValLessThanOrEqualTo(String value) {
            addCriterion("`default_val` <=", value, "defaultVal");
            return (Criteria) this;
        }

        public Criteria andDefaultValLike(String value) {
            addCriterion("`default_val` like", value, "defaultVal");
            return (Criteria) this;
        }

        public Criteria andDefaultValNotLike(String value) {
            addCriterion("`default_val` not like", value, "defaultVal");
            return (Criteria) this;
        }

        public Criteria andDefaultValIn(List<String> values) {
            addCriterion("`default_val` in", values, "defaultVal");
            return (Criteria) this;
        }

        public Criteria andDefaultValNotIn(List<String> values) {
            addCriterion("`default_val` not in", values, "defaultVal");
            return (Criteria) this;
        }

        public Criteria andDefaultValBetween(String value1, String value2) {
            addCriterion("`default_val` between", value1, value2, "defaultVal");
            return (Criteria) this;
        }

        public Criteria andDefaultValNotBetween(String value1, String value2) {
            addCriterion("`default_val` not between", value1, value2, "defaultVal");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNull() {
            addCriterion("`remark` is null");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNotNull() {
            addCriterion("`remark` is not null");
            return (Criteria) this;
        }

        public Criteria andRemarkEqualTo(String value) {
            addCriterion("`remark` =", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotEqualTo(String value) {
            addCriterion("`remark` <>", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThan(String value) {
            addCriterion("`remark` >", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThanOrEqualTo(String value) {
            addCriterion("`remark` >=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThan(String value) {
            addCriterion("`remark` <", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThanOrEqualTo(String value) {
            addCriterion("`remark` <=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLike(String value) {
            addCriterion("`remark` like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotLike(String value) {
            addCriterion("`remark` not like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkIn(List<String> values) {
            addCriterion("`remark` in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotIn(List<String> values) {
            addCriterion("`remark` not in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkBetween(String value1, String value2) {
            addCriterion("`remark` between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotBetween(String value1, String value2) {
            addCriterion("`remark` not between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andValTypeIsNull() {
            addCriterion("`val_type` is null");
            return (Criteria) this;
        }

        public Criteria andValTypeIsNotNull() {
            addCriterion("`val_type` is not null");
            return (Criteria) this;
        }

        public Criteria andValTypeEqualTo(String value) {
            addCriterion("`val_type` =", value, "valType");
            return (Criteria) this;
        }

        public Criteria andValTypeNotEqualTo(String value) {
            addCriterion("`val_type` <>", value, "valType");
            return (Criteria) this;
        }

        public Criteria andValTypeGreaterThan(String value) {
            addCriterion("`val_type` >", value, "valType");
            return (Criteria) this;
        }

        public Criteria andValTypeGreaterThanOrEqualTo(String value) {
            addCriterion("`val_type` >=", value, "valType");
            return (Criteria) this;
        }

        public Criteria andValTypeLessThan(String value) {
            addCriterion("`val_type` <", value, "valType");
            return (Criteria) this;
        }

        public Criteria andValTypeLessThanOrEqualTo(String value) {
            addCriterion("`val_type` <=", value, "valType");
            return (Criteria) this;
        }

        public Criteria andValTypeLike(String value) {
            addCriterion("`val_type` like", value, "valType");
            return (Criteria) this;
        }

        public Criteria andValTypeNotLike(String value) {
            addCriterion("`val_type` not like", value, "valType");
            return (Criteria) this;
        }

        public Criteria andValTypeIn(List<String> values) {
            addCriterion("`val_type` in", values, "valType");
            return (Criteria) this;
        }

        public Criteria andValTypeNotIn(List<String> values) {
            addCriterion("`val_type` not in", values, "valType");
            return (Criteria) this;
        }

        public Criteria andValTypeBetween(String value1, String value2) {
            addCriterion("`val_type` between", value1, value2, "valType");
            return (Criteria) this;
        }

        public Criteria andValTypeNotBetween(String value1, String value2) {
            addCriterion("`val_type` not between", value1, value2, "valType");
            return (Criteria) this;
        }

        public Criteria andKeyEqualTo(boolean condition, String value) {
            if (condition) {
                addCriterion("`key` =", value, "key");
            }
            return (Criteria) this;
        }

        public Criteria andKeyGreaterThanOrEqualTo(boolean condition, String value) {
            if (condition) {
                addCriterion("`key` >=", value, "key");
            }
            return (Criteria) this;
        }

        public Criteria andKeyIn(boolean condition, List<String> value) {
            if (condition) {
                addCriterion("`key` in", value, "key");
            }
            return (Criteria) this;
        }

        public Criteria andValueEqualTo(boolean condition, String value) {
            if (condition) {
                addCriterion("`value` =", value, "value");
            }
            return (Criteria) this;
        }

        public Criteria andValueGreaterThanOrEqualTo(boolean condition, String value) {
            if (condition) {
                addCriterion("`value` >=", value, "value");
            }
            return (Criteria) this;
        }

        public Criteria andValueIn(boolean condition, List<String> value) {
            if (condition) {
                addCriterion("`value` in", value, "value");
            }
            return (Criteria) this;
        }

        public Criteria andDefaultValEqualTo(boolean condition, String value) {
            if (condition) {
                addCriterion("`default_val` =", value, "defaultVal");
            }
            return (Criteria) this;
        }

        public Criteria andDefaultValGreaterThanOrEqualTo(boolean condition, String value) {
            if (condition) {
                addCriterion("`default_val` >=", value, "defaultVal");
            }
            return (Criteria) this;
        }

        public Criteria andDefaultValIn(boolean condition, List<String> value) {
            if (condition) {
                addCriterion("`default_val` in", value, "defaultVal");
            }
            return (Criteria) this;
        }

        public Criteria andRemarkEqualTo(boolean condition, String value) {
            if (condition) {
                addCriterion("`remark` =", value, "remark");
            }
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThanOrEqualTo(boolean condition, String value) {
            if (condition) {
                addCriterion("`remark` >=", value, "remark");
            }
            return (Criteria) this;
        }

        public Criteria andRemarkIn(boolean condition, List<String> value) {
            if (condition) {
                addCriterion("`remark` in", value, "remark");
            }
            return (Criteria) this;
        }

        public Criteria andValTypeEqualTo(boolean condition, String value) {
            if (condition) {
                addCriterion("`val_type` =", value, "valType");
            }
            return (Criteria) this;
        }

        public Criteria andValTypeGreaterThanOrEqualTo(boolean condition, String value) {
            if (condition) {
                addCriterion("`val_type` >=", value, "valType");
            }
            return (Criteria) this;
        }

        public Criteria andValTypeIn(boolean condition, List<String> value) {
            if (condition) {
                addCriterion("`val_type` in", value, "valType");
            }
            return (Criteria) this;
        }
    }

    /**
     * null<p/>
     * BS_Config
     * @date 2021-07-15 12:55:28
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * SystemConfig
     * BS_Config
     * @date 2021-07-15 12:55:28
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}