/**
 * copyright (c) 2020 Kuta Service Framework
 * @author: mybatis generator
 */
package com.kuta.database.mysql.pojo;

import com.kuta.base.annotation.PrimaryKey;
import com.kuta.base.database.KutaDBEntity;
import java.io.Serializable;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table BS_Role
 * @date 2021-03-24 18:00:39
 */
public class Role extends KutaDBEntity implements Serializable {
    /**
     * @desc 角色编号
     * @jdbcType INTEGER
     * @author mybatis generator
     * @date 2021-03-24 18:00:39
     */
    @PrimaryKey
    private Integer rid;

    /**
     * @desc 角色名
     * @jdbcType VARCHAR
     * @author mybatis generator
     * @date 2021-03-24 18:00:39
     */
    private String name;

    /**
     * @desc 部门ID
     * @jdbcType INTEGER
     * @author mybatis generator
     * @date 2021-03-24 18:00:39
     */
    private Integer did;

    /**
     * @desc 简介
     * @jdbcType VARCHAR
     * @author mybatis generator
     * @date 2021-03-24 18:00:39
     */
    private String desc;

    /**
     * @date 2021-03-24 18:00:39
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BS_Role
     * @date 2021-03-24 18:00:39
     */
    public Role(Integer rid, String name, Integer did, String desc) {
        this.rid = rid;
        this.name = name;
        this.did = did;
        this.desc = desc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BS_Role
     * @date 2021-03-24 18:00:39
     */
    public Role() {
        super();
    }

    /**
     * @return rid : 角色编号
     */
    public Integer getRid() {
        return rid;
    }

    /**
     * @param rid : 角色编号
     */
    public void setRid(Integer rid) {
        this.rid = rid;
    }

    /**
     * @return name : 角色名
     */
    public String getName() {
        return name;
    }

    /**
     * @param name : 角色名
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * @return did : 部门ID
     */
    public Integer getDid() {
        return did;
    }

    /**
     * @param did : 部门ID
     */
    public void setDid(Integer did) {
        this.did = did;
    }

    /**
     * @return desc : 简介
     */
    public String getDesc() {
        return desc;
    }

    /**
     * @param desc : 简介
     */
    public void setDesc(String desc) {
        this.desc = desc == null ? null : desc.trim();
    }
}