/**
 * copyright (c) 2020 Kuta Service Framework
 * @author: mybatis generator
 */
package com.kuta.database.mysql.pojo;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class TaskExample {
    /**
     * @date 2021-03-24 18:00:39
     */
    protected String orderByClause;

    /**
     * @date 2021-03-24 18:00:39
     */
    protected boolean distinct;

    /**
     * @date 2021-03-24 18:00:39
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BS_Task
     * @date 2021-03-24 18:00:39
     */
    public TaskExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BS_Task
     * @date 2021-03-24 18:00:39
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BS_Task
     * @date 2021-03-24 18:00:39
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BS_Task
     * @date 2021-03-24 18:00:39
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BS_Task
     * @date 2021-03-24 18:00:39
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BS_Task
     * @date 2021-03-24 18:00:39
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BS_Task
     * @date 2021-03-24 18:00:39
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BS_Task
     * @date 2021-03-24 18:00:39
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BS_Task
     * @date 2021-03-24 18:00:39
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BS_Task
     * @date 2021-03-24 18:00:39
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BS_Task
     * @date 2021-03-24 18:00:39
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * Task
     * BS_Task
     * @date 2021-03-24 18:00:39
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andTidIsNull() {
            addCriterion("`tid` is null");
            return (Criteria) this;
        }

        public Criteria andTidIsNotNull() {
            addCriterion("`tid` is not null");
            return (Criteria) this;
        }

        public Criteria andTidEqualTo(Long value) {
            addCriterion("`tid` =", value, "tid");
            return (Criteria) this;
        }

        public Criteria andTidNotEqualTo(Long value) {
            addCriterion("`tid` <>", value, "tid");
            return (Criteria) this;
        }

        public Criteria andTidGreaterThan(Long value) {
            addCriterion("`tid` >", value, "tid");
            return (Criteria) this;
        }

        public Criteria andTidGreaterThanOrEqualTo(Long value) {
            addCriterion("`tid` >=", value, "tid");
            return (Criteria) this;
        }

        public Criteria andTidLessThan(Long value) {
            addCriterion("`tid` <", value, "tid");
            return (Criteria) this;
        }

        public Criteria andTidLessThanOrEqualTo(Long value) {
            addCriterion("`tid` <=", value, "tid");
            return (Criteria) this;
        }

        public Criteria andTidIn(List<Long> values) {
            addCriterion("`tid` in", values, "tid");
            return (Criteria) this;
        }

        public Criteria andTidNotIn(List<Long> values) {
            addCriterion("`tid` not in", values, "tid");
            return (Criteria) this;
        }

        public Criteria andTidBetween(Long value1, Long value2) {
            addCriterion("`tid` between", value1, value2, "tid");
            return (Criteria) this;
        }

        public Criteria andTidNotBetween(Long value1, Long value2) {
            addCriterion("`tid` not between", value1, value2, "tid");
            return (Criteria) this;
        }

        public Criteria andTimeTypeIsNull() {
            addCriterion("`time_type` is null");
            return (Criteria) this;
        }

        public Criteria andTimeTypeIsNotNull() {
            addCriterion("`time_type` is not null");
            return (Criteria) this;
        }

        public Criteria andTimeTypeEqualTo(Byte value) {
            addCriterion("`time_type` =", value, "timeType");
            return (Criteria) this;
        }

        public Criteria andTimeTypeNotEqualTo(Byte value) {
            addCriterion("`time_type` <>", value, "timeType");
            return (Criteria) this;
        }

        public Criteria andTimeTypeGreaterThan(Byte value) {
            addCriterion("`time_type` >", value, "timeType");
            return (Criteria) this;
        }

        public Criteria andTimeTypeGreaterThanOrEqualTo(Byte value) {
            addCriterion("`time_type` >=", value, "timeType");
            return (Criteria) this;
        }

        public Criteria andTimeTypeLessThan(Byte value) {
            addCriterion("`time_type` <", value, "timeType");
            return (Criteria) this;
        }

        public Criteria andTimeTypeLessThanOrEqualTo(Byte value) {
            addCriterion("`time_type` <=", value, "timeType");
            return (Criteria) this;
        }

        public Criteria andTimeTypeIn(List<Byte> values) {
            addCriterion("`time_type` in", values, "timeType");
            return (Criteria) this;
        }

        public Criteria andTimeTypeNotIn(List<Byte> values) {
            addCriterion("`time_type` not in", values, "timeType");
            return (Criteria) this;
        }

        public Criteria andTimeTypeBetween(Byte value1, Byte value2) {
            addCriterion("`time_type` between", value1, value2, "timeType");
            return (Criteria) this;
        }

        public Criteria andTimeTypeNotBetween(Byte value1, Byte value2) {
            addCriterion("`time_type` not between", value1, value2, "timeType");
            return (Criteria) this;
        }

        public Criteria andCreatedIsNull() {
            addCriterion("`created` is null");
            return (Criteria) this;
        }

        public Criteria andCreatedIsNotNull() {
            addCriterion("`created` is not null");
            return (Criteria) this;
        }

        public Criteria andCreatedEqualTo(Date value) {
            addCriterion("`created` =", value, "created");
            return (Criteria) this;
        }

        public Criteria andCreatedNotEqualTo(Date value) {
            addCriterion("`created` <>", value, "created");
            return (Criteria) this;
        }

        public Criteria andCreatedGreaterThan(Date value) {
            addCriterion("`created` >", value, "created");
            return (Criteria) this;
        }

        public Criteria andCreatedGreaterThanOrEqualTo(Date value) {
            addCriterion("`created` >=", value, "created");
            return (Criteria) this;
        }

        public Criteria andCreatedLessThan(Date value) {
            addCriterion("`created` <", value, "created");
            return (Criteria) this;
        }

        public Criteria andCreatedLessThanOrEqualTo(Date value) {
            addCriterion("`created` <=", value, "created");
            return (Criteria) this;
        }

        public Criteria andCreatedIn(List<Date> values) {
            addCriterion("`created` in", values, "created");
            return (Criteria) this;
        }

        public Criteria andCreatedNotIn(List<Date> values) {
            addCriterion("`created` not in", values, "created");
            return (Criteria) this;
        }

        public Criteria andCreatedBetween(Date value1, Date value2) {
            addCriterion("`created` between", value1, value2, "created");
            return (Criteria) this;
        }

        public Criteria andCreatedNotBetween(Date value1, Date value2) {
            addCriterion("`created` not between", value1, value2, "created");
            return (Criteria) this;
        }

        public Criteria andIsCycleIsNull() {
            addCriterion("`is_cycle` is null");
            return (Criteria) this;
        }

        public Criteria andIsCycleIsNotNull() {
            addCriterion("`is_cycle` is not null");
            return (Criteria) this;
        }

        public Criteria andIsCycleEqualTo(Boolean value) {
            addCriterion("`is_cycle` =", value, "isCycle");
            return (Criteria) this;
        }

        public Criteria andIsCycleNotEqualTo(Boolean value) {
            addCriterion("`is_cycle` <>", value, "isCycle");
            return (Criteria) this;
        }

        public Criteria andIsCycleGreaterThan(Boolean value) {
            addCriterion("`is_cycle` >", value, "isCycle");
            return (Criteria) this;
        }

        public Criteria andIsCycleGreaterThanOrEqualTo(Boolean value) {
            addCriterion("`is_cycle` >=", value, "isCycle");
            return (Criteria) this;
        }

        public Criteria andIsCycleLessThan(Boolean value) {
            addCriterion("`is_cycle` <", value, "isCycle");
            return (Criteria) this;
        }

        public Criteria andIsCycleLessThanOrEqualTo(Boolean value) {
            addCriterion("`is_cycle` <=", value, "isCycle");
            return (Criteria) this;
        }

        public Criteria andIsCycleIn(List<Boolean> values) {
            addCriterion("`is_cycle` in", values, "isCycle");
            return (Criteria) this;
        }

        public Criteria andIsCycleNotIn(List<Boolean> values) {
            addCriterion("`is_cycle` not in", values, "isCycle");
            return (Criteria) this;
        }

        public Criteria andIsCycleBetween(Boolean value1, Boolean value2) {
            addCriterion("`is_cycle` between", value1, value2, "isCycle");
            return (Criteria) this;
        }

        public Criteria andIsCycleNotBetween(Boolean value1, Boolean value2) {
            addCriterion("`is_cycle` not between", value1, value2, "isCycle");
            return (Criteria) this;
        }

        public Criteria andNextRunTimeIsNull() {
            addCriterion("`next_run_time` is null");
            return (Criteria) this;
        }

        public Criteria andNextRunTimeIsNotNull() {
            addCriterion("`next_run_time` is not null");
            return (Criteria) this;
        }

        public Criteria andNextRunTimeEqualTo(Date value) {
            addCriterion("`next_run_time` =", value, "nextRunTime");
            return (Criteria) this;
        }

        public Criteria andNextRunTimeNotEqualTo(Date value) {
            addCriterion("`next_run_time` <>", value, "nextRunTime");
            return (Criteria) this;
        }

        public Criteria andNextRunTimeGreaterThan(Date value) {
            addCriterion("`next_run_time` >", value, "nextRunTime");
            return (Criteria) this;
        }

        public Criteria andNextRunTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("`next_run_time` >=", value, "nextRunTime");
            return (Criteria) this;
        }

        public Criteria andNextRunTimeLessThan(Date value) {
            addCriterion("`next_run_time` <", value, "nextRunTime");
            return (Criteria) this;
        }

        public Criteria andNextRunTimeLessThanOrEqualTo(Date value) {
            addCriterion("`next_run_time` <=", value, "nextRunTime");
            return (Criteria) this;
        }

        public Criteria andNextRunTimeIn(List<Date> values) {
            addCriterion("`next_run_time` in", values, "nextRunTime");
            return (Criteria) this;
        }

        public Criteria andNextRunTimeNotIn(List<Date> values) {
            addCriterion("`next_run_time` not in", values, "nextRunTime");
            return (Criteria) this;
        }

        public Criteria andNextRunTimeBetween(Date value1, Date value2) {
            addCriterion("`next_run_time` between", value1, value2, "nextRunTime");
            return (Criteria) this;
        }

        public Criteria andNextRunTimeNotBetween(Date value1, Date value2) {
            addCriterion("`next_run_time` not between", value1, value2, "nextRunTime");
            return (Criteria) this;
        }

        public Criteria andCronExpIsNull() {
            addCriterion("`cron_exp` is null");
            return (Criteria) this;
        }

        public Criteria andCronExpIsNotNull() {
            addCriterion("`cron_exp` is not null");
            return (Criteria) this;
        }

        public Criteria andCronExpEqualTo(String value) {
            addCriterion("`cron_exp` =", value, "cronExp");
            return (Criteria) this;
        }

        public Criteria andCronExpNotEqualTo(String value) {
            addCriterion("`cron_exp` <>", value, "cronExp");
            return (Criteria) this;
        }

        public Criteria andCronExpGreaterThan(String value) {
            addCriterion("`cron_exp` >", value, "cronExp");
            return (Criteria) this;
        }

        public Criteria andCronExpGreaterThanOrEqualTo(String value) {
            addCriterion("`cron_exp` >=", value, "cronExp");
            return (Criteria) this;
        }

        public Criteria andCronExpLessThan(String value) {
            addCriterion("`cron_exp` <", value, "cronExp");
            return (Criteria) this;
        }

        public Criteria andCronExpLessThanOrEqualTo(String value) {
            addCriterion("`cron_exp` <=", value, "cronExp");
            return (Criteria) this;
        }

        public Criteria andCronExpLike(String value) {
            addCriterion("`cron_exp` like", value, "cronExp");
            return (Criteria) this;
        }

        public Criteria andCronExpNotLike(String value) {
            addCriterion("`cron_exp` not like", value, "cronExp");
            return (Criteria) this;
        }

        public Criteria andCronExpIn(List<String> values) {
            addCriterion("`cron_exp` in", values, "cronExp");
            return (Criteria) this;
        }

        public Criteria andCronExpNotIn(List<String> values) {
            addCriterion("`cron_exp` not in", values, "cronExp");
            return (Criteria) this;
        }

        public Criteria andCronExpBetween(String value1, String value2) {
            addCriterion("`cron_exp` between", value1, value2, "cronExp");
            return (Criteria) this;
        }

        public Criteria andCronExpNotBetween(String value1, String value2) {
            addCriterion("`cron_exp` not between", value1, value2, "cronExp");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("`status` is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("`status` is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(String value) {
            addCriterion("`status` =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(String value) {
            addCriterion("`status` <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(String value) {
            addCriterion("`status` >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(String value) {
            addCriterion("`status` >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(String value) {
            addCriterion("`status` <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(String value) {
            addCriterion("`status` <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLike(String value) {
            addCriterion("`status` like", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotLike(String value) {
            addCriterion("`status` not like", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<String> values) {
            addCriterion("`status` in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<String> values) {
            addCriterion("`status` not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(String value1, String value2) {
            addCriterion("`status` between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(String value1, String value2) {
            addCriterion("`status` not between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andTidEqualTo(boolean condition, Long value) {
            if (condition) {
                addCriterion("`tid` =", value, "tid");
            }
            return (Criteria) this;
        }

        public Criteria andTidGreaterThanOrEqualTo(boolean condition, Long value) {
            if (condition) {
                addCriterion("`tid` >=", value, "tid");
            }
            return (Criteria) this;
        }

        public Criteria andTidIn(boolean condition, List<Long> value) {
            if (condition) {
                addCriterion("`tid` in", value, "tid");
            }
            return (Criteria) this;
        }

        public Criteria andTimeTypeEqualTo(boolean condition, Byte value) {
            if (condition) {
                addCriterion("`time_type` =", value, "timeType");
            }
            return (Criteria) this;
        }

        public Criteria andTimeTypeGreaterThanOrEqualTo(boolean condition, Byte value) {
            if (condition) {
                addCriterion("`time_type` >=", value, "timeType");
            }
            return (Criteria) this;
        }

        public Criteria andTimeTypeIn(boolean condition, List<Byte> value) {
            if (condition) {
                addCriterion("`time_type` in", value, "timeType");
            }
            return (Criteria) this;
        }

        public Criteria andCreatedEqualTo(boolean condition, Date value) {
            if (condition) {
                addCriterion("`created` =", value, "created");
            }
            return (Criteria) this;
        }

        public Criteria andCreatedGreaterThanOrEqualTo(boolean condition, Date value) {
            if (condition) {
                addCriterion("`created` >=", value, "created");
            }
            return (Criteria) this;
        }

        public Criteria andCreatedIn(boolean condition, List<Date> value) {
            if (condition) {
                addCriterion("`created` in", value, "created");
            }
            return (Criteria) this;
        }

        public Criteria andIsCycleEqualTo(boolean condition, Boolean value) {
            if (condition) {
                addCriterion("`is_cycle` =", value, "isCycle");
            }
            return (Criteria) this;
        }

        public Criteria andIsCycleGreaterThanOrEqualTo(boolean condition, Boolean value) {
            if (condition) {
                addCriterion("`is_cycle` >=", value, "isCycle");
            }
            return (Criteria) this;
        }

        public Criteria andIsCycleIn(boolean condition, List<Boolean> value) {
            if (condition) {
                addCriterion("`is_cycle` in", value, "isCycle");
            }
            return (Criteria) this;
        }

        public Criteria andNextRunTimeEqualTo(boolean condition, Date value) {
            if (condition) {
                addCriterion("`next_run_time` =", value, "nextRunTime");
            }
            return (Criteria) this;
        }

        public Criteria andNextRunTimeGreaterThanOrEqualTo(boolean condition, Date value) {
            if (condition) {
                addCriterion("`next_run_time` >=", value, "nextRunTime");
            }
            return (Criteria) this;
        }

        public Criteria andNextRunTimeIn(boolean condition, List<Date> value) {
            if (condition) {
                addCriterion("`next_run_time` in", value, "nextRunTime");
            }
            return (Criteria) this;
        }

        public Criteria andCronExpEqualTo(boolean condition, String value) {
            if (condition) {
                addCriterion("`cron_exp` =", value, "cronExp");
            }
            return (Criteria) this;
        }

        public Criteria andCronExpGreaterThanOrEqualTo(boolean condition, String value) {
            if (condition) {
                addCriterion("`cron_exp` >=", value, "cronExp");
            }
            return (Criteria) this;
        }

        public Criteria andCronExpIn(boolean condition, List<String> value) {
            if (condition) {
                addCriterion("`cron_exp` in", value, "cronExp");
            }
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(boolean condition, String value) {
            if (condition) {
                addCriterion("`status` =", value, "status");
            }
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(boolean condition, String value) {
            if (condition) {
                addCriterion("`status` >=", value, "status");
            }
            return (Criteria) this;
        }

        public Criteria andStatusIn(boolean condition, List<String> value) {
            if (condition) {
                addCriterion("`status` in", value, "status");
            }
            return (Criteria) this;
        }
    }

    /**
     * null<p/>
     * BS_Task
     * @date 2021-03-24 18:00:39
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * Task
     * BS_Task
     * @date 2021-03-24 18:00:39
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}