/**
 * copyright (c) 2020 Kuta Service Framework
 * @author: mybatis generator
 */
package com.kuta.database.mysql.pojo;

import com.kuta.base.annotation.PrimaryKey;
import com.kuta.database.mysql.pojo.extend.UserBase;
import java.io.Serializable;
import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table BS_User
 * @date 2021-03-24 18:00:39
 */
public class User extends UserBase implements Serializable {
    /**
     * @desc 
     * @jdbcType INTEGER
     * @author mybatis generator
     * @date 2021-03-24 18:00:39
     */
    @PrimaryKey
    private Integer uid;

    /**
     * @desc 账号
     * @jdbcType VARCHAR
     * @author mybatis generator
     * @date 2021-03-24 18:00:39
     */
    private String account;

    /**
     * @desc 昵称
     * @jdbcType VARCHAR
     * @author mybatis generator
     * @date 2021-03-24 18:00:39
     */
    private String nick;

    /**
     * @desc 名字
     * @jdbcType VARCHAR
     * @author mybatis generator
     * @date 2021-03-24 18:00:39
     */
    private String name;

    /**
     * @desc 密码
     * @jdbcType VARCHAR
     * @author mybatis generator
     * @date 2021-03-24 18:00:39
     */
    private String password;

    /**
     * @desc 创建时间
     * @jdbcType TIMESTAMP
     * @author mybatis generator
     * @date 2021-03-24 18:00:39
     */
    private Date created;

    /**
     * @desc 最后登录时间
     * @jdbcType TIMESTAMP
     * @author mybatis generator
     * @date 2021-03-24 18:00:39
     */
    private Date lastLogin;

    /**
     * @desc 手机号
     * @jdbcType VARCHAR
     * @author mybatis generator
     * @date 2021-03-24 18:00:39
     */
    private String phone;

    /**
     * @desc 状态
     * @jdbcType VARCHAR
     * @author mybatis generator
     * @date 2021-03-24 18:00:39
     */
    private String status;

    /**
     * @desc 是否超级管理员
     * @jdbcType BIT
     * @author mybatis generator
     * @date 2021-03-24 18:00:39
     */
    private Boolean isSuper;

    /**
     * @desc 头像地址
     * @jdbcType VARCHAR
     * @author mybatis generator
     * @date 2021-03-24 18:00:39
     */
    private String avatar;

    /**
     * @desc 部门编号
     * @jdbcType INTEGER
     * @author mybatis generator
     * @date 2021-03-24 18:00:39
     */
    private Integer did;

    /**
     * @desc 
     * @jdbcType TIMESTAMP
     * @author mybatis generator
     * @date 2021-03-24 18:00:39
     */
    private Date lastOnline;

    /**
     * @date 2021-03-24 18:00:39
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BS_User
     * @date 2021-03-24 18:00:39
     */
    public User(Integer uid, String account, String nick, String name, String password, Date created, Date lastLogin, String phone, String status, Boolean isSuper, String avatar, Integer did, Date lastOnline) {
        this.uid = uid;
        this.account = account;
        this.nick = nick;
        this.name = name;
        this.password = password;
        this.created = created;
        this.lastLogin = lastLogin;
        this.phone = phone;
        this.status = status;
        this.isSuper = isSuper;
        this.avatar = avatar;
        this.did = did;
        this.lastOnline = lastOnline;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BS_User
     * @date 2021-03-24 18:00:39
     */
    public User() {
        super();
    }

    /**
     * @return uid : 
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * @param uid : 
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    /**
     * @return account : 账号
     */
    public String getAccount() {
        return account;
    }

    /**
     * @param account : 账号
     */
    public void setAccount(String account) {
        this.account = account == null ? null : account.trim();
    }

    /**
     * @return nick : 昵称
     */
    public String getNick() {
        return nick;
    }

    /**
     * @param nick : 昵称
     */
    public void setNick(String nick) {
        this.nick = nick == null ? null : nick.trim();
    }

    /**
     * @return name : 名字
     */
    public String getName() {
        return name;
    }

    /**
     * @param name : 名字
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * @return password : 密码
     */
    public String getPassword() {
        return password;
    }

    /**
     * @param password : 密码
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * @return created : 创建时间
     */
    public Date getCreated() {
        return created;
    }

    /**
     * @param created : 创建时间
     */
    public void setCreated(Date created) {
        this.created = created;
    }

    /**
     * @return lastLogin : 最后登录时间
     */
    public Date getLastLogin() {
        return lastLogin;
    }

    /**
     * @param lastLogin : 最后登录时间
     */
    public void setLastLogin(Date lastLogin) {
        this.lastLogin = lastLogin;
    }

    /**
     * @return phone : 手机号
     */
    public String getPhone() {
        return phone;
    }

    /**
     * @param phone : 手机号
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * @return status : 状态
     */
    public String getStatus() {
        return status;
    }

    /**
     * @param status : 状态
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * @return isSuper : 是否超级管理员
     */
    public Boolean getIsSuper() {
        return isSuper;
    }

    /**
     * @param isSuper : 是否超级管理员
     */
    public void setIsSuper(Boolean isSuper) {
        this.isSuper = isSuper;
    }

    /**
     * @return avatar : 头像地址
     */
    public String getAvatar() {
        return avatar;
    }

    /**
     * @param avatar : 头像地址
     */
    public void setAvatar(String avatar) {
        this.avatar = avatar == null ? null : avatar.trim();
    }

    /**
     * @return did : 部门编号
     */
    public Integer getDid() {
        return did;
    }

    /**
     * @param did : 部门编号
     */
    public void setDid(Integer did) {
        this.did = did;
    }

    /**
     * @return lastOnline : 
     */
    public Date getLastOnline() {
        return lastOnline;
    }

    /**
     * @param lastOnline : 
     */
    public void setLastOnline(Date lastOnline) {
        this.lastOnline = lastOnline;
    }
}